import { Product } from './types';

export const CATEGORIES = [
  { id: 'electronics', name: 'Elektronika', icon: 'devices' },
  { id: 'fashion', name: 'Kiyim va Aksessuarlar', icon: 'apparel' },
  { id: 'home', name: 'Uy va Ro‘zg‘or', icon: 'home' },
  { id: 'beauty', name: 'Go‘zallik va Parvarish', icon: 'auto_awesome' },
  { id: 'sports', name: 'Sport va Hordiq', icon: 'fitness_center' },
];

export const PRODUCTS: Product[] = [
  // --- ELECTRONICS (20 items) ---
  {
    id: 'elec-pow-1',
    name: 'Anker Powerline Mini 10000mAh Powerbank',
    brand: 'Anker',
    price: 345000,
    rating: 4.8,
    reviewsCount: 124,
    image: 'https://images.unsplash.com/photo-1609592424109-dd9a9e229f3d?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Telefonlarni tezkor va xavfsiz zaryadlovchi ixcham premium tashqi quvvatlantirgich.',
    specs: { battery: '10000 mAh', charging: 'Type-C PD 20W', weight: '180g' }
  },
  {
    id: 'elec-cab-1',
    name: 'Ugreen Type-C 100W Tezkor Zaryadlovchi Kabel',
    brand: 'Ugreen',
    price: 95000,
    rating: 4.9,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1541667593101-0853ad25ab5c?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Noutbuk va telefonlar uchun mustahkam neylon to‘qimali, yuqori tezlikdagi kabel.',
    specs: { range: '2 Metr', charging: '100W Max', weight: '45g' }
  },
  {
    id: 'elec-mou-1',
    name: 'Logitech Pebble M350 Simsiz Sichqoncha',
    brand: 'Logitech',
    price: 280000,
    rating: 4.7,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Ovoz chiqarmaydigan, tahrir va ofis ishlari uchun juda qulay, ultra-ixcham simsiz sichqoncha.',
    specs: { battery: '18 Oy', range: '10 Metr', weight: '78g' }
  },
  {
    id: 'elec-rgb-pad',
    name: 'Razer Goliathus RGB Premium Sichqoncha Gilamchasi',
    brand: 'Razer',
    price: 350000,
    rating: 4.8,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Yorqin geymerlar uchun RGB yoritgichli, silliq harakatlanishni ta’minlovchi gilamcha.',
    specs: { range: 'RGB Chiroqli', weight: '340g' }
  },
  {
    id: 'elec-stand-1',
    name: 'Baseus Metall Bukiladigan Telefon Stendi',
    brand: 'Baseus',
    price: 120000,
    rating: 4.6,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Yuzani tirnamaydigan silikon qatlamli, har xil burchakka moslashuvchan alyuminiy telefon ushlagich.',
    specs: { weight: '150g', isolation: 'Sirpanmaydigan silikon' }
  },
  {
    id: 'elec-hub-1',
    name: 'Baseus 4-in-1 USB Hub Port Ko‘paytirgich',
    brand: 'Baseus',
    price: 185000,
    rating: 4.7,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Bir vaqtning o‘zida to‘rtta qurilmani ulash imkonini beruvchi alyuminiy korpusli hub.',
    specs: { range: 'USB 3.0 / USB-C', speed: '5Gbps', weight: '45g' }
  },
  {
    id: 'elec-fan-1',
    name: 'Joyroom Portativ Stol Mini Ventilyatori',
    brand: 'Joyroom',
    price: 150000,
    rating: 4.5,
    reviewsCount: 75,
    image: 'https://images.unsplash.com/photo-1618944847828-82e943c3bddf?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Yozning issiq kunlarida ish stolingiz uchun past shovqinli, batareyali mini ventilyator.',
    specs: { battery: '6 Soat', charging: 'USB Zaryadlash', weight: '120g' }
  },
  {
    id: 'elec-carg-head',
    name: 'Ugreen GaN 30W Super Tezkor Adapter',
    brand: 'Ugreen',
    price: 220000,
    rating: 4.9,
    reviewsCount: 195,
    image: 'https://images.unsplash.com/photo-1622445262465-2481c4574875?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Ilg‘or GaN texnologiyasiga ega, qizib ketishdan himoyalangan o‘ta ixcham zaryadlash boshi.',
    specs: { charging: 'PD 30W Fast', weight: '55g', protection: 'Aqlli chip himoyasi' }
  },
  {
    id: 'elec-stylus-1',
    name: 'Baseus universal planshet stilyusi (Ruchka)',
    brand: 'Baseus',
    price: 210000,
    rating: 4.4,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Barcha sensorli ekranli planshet va telefonlar uchun nozik yozuvchi passiv stilyus ruchkasi.',
    specs: { weight: '15g', design: 'Alyuminiy korpus' }
  },
  {
    id: 'elec-led-strip',
    name: 'Smart RGB LED Chiroqli Lenta (5 metr)',
    brand: 'LuxeLight',
    price: 135000,
    rating: 4.6,
    reviewsCount: 220,
    image: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Xonani bezatish uchun pult yordamida boshqariladigan rang-barang yorqin chiroqli lenta.',
    specs: { range: '5 Metr', lightModes: '16 Xil Ranglar', weight: '110g' }
  },
  {
    id: 'elec-earphones-1',
    name: 'Lenovo Thinkplus LivePods LP40 Simsiz Quloqchin',
    brand: 'Lenovo',
    price: 175000,
    rating: 4.5,
    reviewsCount: 450,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Yengil va tiniq ovozga ega, kundalik foydalanish uchun Bluetooth quloqchinlar.',
    specs: { battery: '20 Soat (Keys bilan)', range: '10 Metr', weight: '35g' }
  },
  {
    id: 'elec-sd-1',
    name: 'Kingston 128GB MicroSD Tezkor Xotira Kartasi',
    brand: 'Kingston',
    price: 190000,
    rating: 4.8,
    reviewsCount: 180,
    image: 'https://images.unsplash.com/photo-1558486245-12cf5cbd19b5?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'FullHD va 4K videolar yozishni qo‘llab-quvvatlovchi yuqori tezlikdagi xotira chipi.',
    specs: { speed: '100MB/s Read', weight: '2g', protection: 'Suv va rentgen himoyasi' }
  },
  {
    id: 'elec-ring-light',
    name: 'Stol usti selfi ring-lampasi (Shtativ bilan)',
    brand: 'PhotoPro',
    price: 240000,
    rating: 4.7,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1595856489768-4a208252a57b?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Tik-Tok va blogerlar uchun oq, issiq va aralash yoritish rejimiga ega doiraviy chiroq.',
    specs: { range: '3 Xil Rang harorati', charging: 'USB 5V', weight: '450g' }
  },
  {
    id: 'elec-bt-spk',
    name: 'Xiaomi Mi Portable Mini Bluetooth Kolonka',
    brand: 'Xiaomi',
    price: 295000,
    rating: 4.8,
    reviewsCount: 290,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Suvga chidamli (IP67), hovuz bo‘yi va tabiat qo‘ynida musiqa tinglash uchun mo‘ljallangan ixcham dinamik.',
    specs: { battery: '10 Soat', range: 'Bluetooth 5.0', weight: '185g' }
  },
  {
    id: 'elec-organizer',
    name: 'Baseus Kabellar va Zaryadchilar uchun G‘ilof',
    brand: 'Baseus',
    price: 85000,
    rating: 4.6,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1622445262465-2481c4574875?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Sayohatlarda telefon quvvatgichlari va simlarni guruhlash uchun suvga chidamli maxsus sumkacha.',
    specs: { weight: '80g', isolation: 'Suv o‘tkazmaydigan neylon' }
  },
  {
    id: 'elec-smart-plug',
    name: 'Tuya Smart Wi-Fi Aqlli Rozetka (Pultli)',
    brand: 'Tuya',
    price: 140000,
    rating: 4.7,
    reviewsCount: 135,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Sizning telefon ilovangiz orqali uydagi jihozlarni masofadan yoqib-o‘chiruvchi aqlli rozetka.',
    specs: { range: 'Wi-Fi 2.4GHz', load: '16A Max', weight: '90g' }
  },
  {
    id: 'elec-stand-wood',
    name: 'Tabiiy Yong‘oq yog‘ochidan qilingan Quloqchin Stendi',
    brand: 'WoodArt',
    price: 215000,
    rating: 4.9,
    reviewsCount: 24,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Ish stolingiz ko‘rkiga ko‘rk qo‘shadigan, nafis ishlangan ekologik yog‘och quloqchin ushlagichi.',
    specs: { weight: '220g', material: 'Yong‘oq daraxti' }
  },
  {
    id: 'elec-clean-kit',
    name: 'Klaviatura va Monitorlar uchun tozalovchi sprey + cho‘tka',
    brand: 'CleanMax',
    price: 45000,
    rating: 4.5,
    reviewsCount: 115,
    image: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Noutbuk ekranlari, sensorli panellar va klaviatura orasidagi changlarni tozalash uchun Universal to‘plam.',
    specs: { weight: '120g', capacity: '100ml' }
  },
  {
    id: 'elec-aux',
    name: 'Ugreen Metal Raz’emli Premium AUX Kabel',
    brand: 'Ugreen',
    price: 55000,
    rating: 4.8,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1541667593101-0853ad25ab5c?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Avtomobilda yuqori sifatli musiqa his etish uchun tilla suvi yugurtirilgan 3.5mm audio kabel.',
    specs: { range: '1.2 Metr', weight: '25g' }
  },
  {
    id: 'elec-car-holder',
    name: 'Xiaomi Mi Simsiz Avto-telefon Ushtargich',
    brand: 'Xiaomi',
    price: 410000,
    rating: 4.7,
    reviewsCount: 160,
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Mashina panjarasiga mahkam qotib turadigan, infraqizil datchikli va mahkamlagichli ushlagich.',
    specs: { charging: '10W Simsiz zaryad', weight: '130g' }
  },

  // --- FASHION (20 items) ---
  {
    id: 'fash-wallet-1',
    name: 'Erkaklar uchun klassik charm hamyon',
    brand: 'LuxeLeather',
    price: 245000,
    rating: 4.8,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Yuz foiz tabiiy charm va RFID-himoyaga ega nafis va sig‘imli erkaklar hamyoni.',
    specs: { weight: '85g', material: 'Haqiqiy charm' }
  },
  {
    id: 'fash-cap-1',
    name: 'Sportiv yozgi oq kepka (Unisex)',
    brand: 'StyleUp',
    price: 110000,
    rating: 4.6,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Havo o‘tkazuvchi paxtali matodan ishlangan, quyosh nurlaridan mukammal himoya qiluvchi sport bosh kiyimi.',
    specs: { weight: '60g', material: '100% paxta' }
  },
  {
    id: 'fash-glasses-1',
    name: 'Polaritlangan Klassik Quyosh Ko‘zoynagi',
    brand: 'RayVibe',
    price: 295000,
    rating: 4.7,
    reviewsCount: 130,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Ko‘zni ultrabinafsha nurlardan UV450 darajasida asraydigan, zamon bilan hamnafas ko‘zoynak.',
    specs: { weight: '28g', protection: 'UV400 Polarized' }
  },
  {
    id: 'fash-socks-pack',
    name: 'Erkaklar uchun paxtali paypoqlar to‘plami (5 juft)',
    brand: 'CottonFit',
    price: 65000,
    rating: 4.8,
    reviewsCount: 320,
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Hidsiz va terlatmaydigan, sport va kundalik poyabzal uchun nozik sifatli paypoqlar.',
    specs: { size: '39-44 universal', weight: '120g' }
  },
  {
    id: 'fash-tote-1',
    name: 'Tabiiy matodan tikilgan eko-sumka (Tote Bag)',
    brand: 'EcoEarth',
    price: 45000,
    rating: 4.9,
    reviewsCount: 165,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Dars, xaridlar va sayr uchun juda mos keladigan keng va bejirim paxtali ekologik sumka.',
    specs: { weight: '90g', load: '10kggacha' }
  },
  {
    id: 'fash-belt-1',
    name: 'Elegant quyma metall qisqichli charm kamar',
    brand: 'Legend',
    price: 195000,
    rating: 4.6,
    reviewsCount: 74,
    image: 'https://images.unsplash.com/photo-1624222247344-550fb805296f?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Klassik va zamonaviy shimlar uchun mos keladigan mustahkam silliq charm kamar.',
    specs: { weight: '140g', length: '115 - 125 sm' }
  },
  {
    id: 'fash-tshirt-1',
    name: 'Klassik tekis rangli yozgi T-shirt (Qora)',
    brand: 'BasicFit',
    price: 90000,
    rating: 4.7,
    reviewsCount: 198,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Yuqori sifatli trikotaj paxtadan ishlangan, rangi o‘chmaydigan oddiy va qulay futbolka.',
    specs: { weight: '150g', material: '95% Paxta, 5% Likra' }
  },
  {
    id: 'fash-cardholder',
    name: 'Ultra-ingichka alyuminiy kart-holder (Hamyon)',
    brand: 'SecureCard',
    price: 125000,
    rating: 4.8,
    reviewsCount: 85,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Plastik kartalarni himoya qiluvchi va bitta tugma bosish orqali chiqarib beruvchi aqlli moslama.',
    specs: { weight: '48g', capacity: '6-8 Karta' }
  },
  {
    id: 'fash-slippers',
    name: 'Yumshoq uy shippaklari (Yozgi/Ortopedik)',
    brand: 'ComfortHome',
    price: 75000,
    rating: 4.5,
    reviewsCount: 63,
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Oyoqni toliqtirmaydigan, yuvish oson bo‘lgan ortopedik rezina uy shippaklari.',
    specs: { weight: '160g', material: 'EVA ko‘pik' }
  },
  {
    id: 'fash-bracelet',
    name: 'Nafis tabiiy toshlardan yasalgan Erkaklar bilaguzugi',
    brand: 'StoneVibe',
    price: 80000,
    rating: 4.6,
    reviewsCount: 41,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Vulkanik lava toshlaridan ishlangan, elastik rezinali zamonaviy erkaklar bilak bezagi.',
    specs: { weight: '22g', material: 'Lava va Agat toshlari' }
  },
  {
    id: 'fash-backpack',
    name: 'Suv o‘tkazmaydigan shahar noutbuk Orqa Sumkasi',
    brand: 'Apex',
    price: 340000,
    rating: 4.8,
    reviewsCount: 92,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Kundalik ish yoki darsga borish uchun ideal, 15.6 dyuymli noutbuk uchun himoyali bo‘lmali ryukzak.',
    specs: { weight: '650g', volume: '20 Litr' }
  },
  {
    id: 'fash-scarf',
    name: 'Kuzgi nozik kashmiri ayollar ro‘moli',
    brand: 'Grace',
    price: 135000,
    rating: 4.7,
    reviewsCount: 51,
    image: 'https://images.unsplash.com/photo-1584030373081-f37b7bb4fa8e?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Yumshoq kashmir junidan to‘qilgan, jozibador rangli va sovuqdan asrovchi ayollar ro‘moli.',
    specs: { weight: '180g', dimensions: '180x40 sm' }
  },
  {
    id: 'fash-pouch',
    name: 'Ayollar uchun kosmetika va aksessuarlar sumkachasi',
    brand: 'CosmoBag',
    price: 95000,
    rating: 4.7,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Barcha gigiyenik va pardoz vositalarini tartibli saqlash uchun qulay va suvga chidamli g‘ilof sumka.',
    specs: { weight: '95g', pocketCount: '4 bo‘lim' }
  },
  {
    id: 'fash-panama',
    name: 'Yozgi quyosh nurlariga qarshi Panama shlyapasi',
    brand: 'BeachSun',
    price: 85000,
    rating: 4.5,
    reviewsCount: 45,
    image: 'https://images.unsplash.com/photo-1576871337622-98d48d4aa53e?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Tabiatga va plyajga chiqishda quyosh urishidan saqlovchi paxtali bukiluvchan panama.',
    specs: { weight: '55g', material: 'Yuviluvchi Paxta' }
  },
  {
    id: 'fash-keychain',
    name: 'Premium po‘lat va charm avtomobil kalit kaliti',
    brand: 'LuxeKey',
    price: 55000,
    rating: 4.8,
    reviewsCount: 160,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Pult va kalitlarni translatesiz mustahkamlovchi, mustahkam karabinli charm brelok.',
    specs: { weight: '25g', material: 'Zanglamas po‘lat' }
  },
  {
    id: 'fash-ring',
    name: 'Minimalistik Kumush uzuk (Titanium po‘lat)',
    brand: 'SteelFashion',
    price: 95000,
    rating: 4.6,
    reviewsCount: 37,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Rangi o‘chmaydigan va allergik reaksiyalar qo‘zg‘atmaydigan tibbiy titanium po‘latdan yasalgan uzuk.',
    specs: { weight: '6g', size: '18-21 o‘lcham' }
  },
  {
    id: 'fash-hairbands',
    name: 'Ipak soch bog‘ichlari to‘plami (3 xil rangda)',
    brand: 'SilkyWay',
    price: 40000,
    rating: 4.9,
    reviewsCount: 194,
    image: 'https://images.unsplash.com/photo-1582234373400-3400-3400e99f0e7f?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Sochni sindirmaydigan va zarar yetkazmaydigan tabiiy ipakdan ishlangan soch bog‘ichlari.',
    specs: { weight: '12g', material: 'Tabiiy ipak' }
  },
  {
    id: 'fash-watch-box',
    name: 'Soatlar saqlash uchun zamonaviy charm quti',
    brand: 'ClassicBox',
    price: 260000,
    rating: 4.8,
    reviewsCount: 29,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Oila yoki do‘stlar uchun ajoyib sovg‘a, 6 ta qo‘l soatiga mo‘ljallangan oynali nufuzli ko‘rgazma qutisi.',
    specs: { weight: '950g', materials: 'PU Charm + Shisha' }
  },
  {
    id: 'fash-canvas-belt',
    name: 'Sportiv neylon tasma matoli tezkor kamar',
    brand: 'Tactical',
    price: 95000,
    rating: 4.5,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1624222247344-550fb805296f?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Dala poygalari, baliq ovlash yoki jinsi shimlar uchun juda qulay avtomat-plastik qisqichli kamar.',
    specs: { weight: '110g', length: '120 sm' }
  },
  {
    id: 'fash-wallet-lady',
    name: 'Ayollar uchun ixcham bejirim hamyon (Pushti)',
    brand: 'PinkLuxe',
    price: 185000,
    rating: 4.7,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Kichik sumkachalarga ham osongina sig‘adigan nafis yumshoq matli hamyon.',
    specs: { weight: '70g', compartments: 'Karta va Tanga bo‘limlari' }
  },

  // --- HOME (20 items) ---
  {
    id: 'home-mug-1',
    name: 'Premium keramik chiroyli qahva finjoni',
    brand: 'HomePot',
    price: 75000,
    rating: 4.9,
    reviewsCount: 240,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Yumshoq skandinavcha dizayn asosida tayyorlangan, haroratni uzoq vaqt ushlab turuvchi chinni kofein finjoni.',
    specs: { capacity: '350ml', weight: '280g' }
  },
  {
    id: 'home-candle-1',
    name: 'Tabiiy soya mumidan atirlangan xushbo‘y sham',
    brand: 'AromaHome',
    price: 95000,
    rating: 4.8,
    reviewsCount: 180,
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Xonani sokinlik va osoyishtalik bilan to‘ldiruvchi, vanil va lavanda afsonaviy hidini taratuvchi sham.',
    specs: { burnTime: '30 Soat', weight: '200g' }
  },
  {
    id: 'home-clock-1',
    name: 'Yog‘ochli Skandinav uslubidagi devor soati',
    brand: 'NordicWood',
    price: 320000,
    rating: 4.7,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Matli va mutlaqo shovqinsiz ishlaydigan mexanizmga ega ekologik yog‘ochli zamonaviy soat.',
    specs: { diameter: '30 sm', weight: '450g' }
  },
  {
    id: 'home-pillow',
    name: 'Yumshoq ortopedik dam olish yostig‘i',
    brand: 'ComfortSleep',
    price: 280000,
    rating: 4.9,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Bo‘yin umurtqasini dam olish paytida to‘g‘ri ushlovchi Memory Foam xotira effektili yostiq.',
    specs: { dimensions: '50x30 sm', weight: '600g' }
  },
  {
    id: 'home-humidifier',
    name: 'Smart xonani namlantiruvchi va atir diffuzori',
    brand: 'PureAir',
    price: 240000,
    rating: 4.6,
    reviewsCount: 195,
    image: 'https://images.unsplash.com/photo-1519183071298-a2962feb14f4?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Bolalar xonasi va yotoqxona havosi namligini saqlash uchun chiroyli RGB tungi chiroqli ultratovushli namlagich.',
    specs: { capacity: '500ml', battery: 'Tarmoq orqali', weight: '250g' }
  },
  {
    id: 'home-organizer-desk',
    name: 'Stol usti hujjatlar va ofis anjomlari saqlagichi',
    brand: 'NordicOffice',
    price: 135000,
    rating: 4.7,
    reviewsCount: 41,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Ish joyingizdagi qalam, daftarlar va mayda-chuyda vositalarni tartiblash uchun metall to‘rli polochka.',
    specs: { weight: '800g', material: 'Temir karkas' }
  },
  {
    id: 'home-thermos',
    name: 'Zanglamaydigan po‘lat suv va choy termosi',
    brand: 'ThermosPro',
    price: 165000,
    rating: 4.8,
    reviewsCount: 120,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Issiq choy yoki yaxna ichimliklarni 12 soatgacha o‘z haroratida saqlab beruvchi vakuum termos.',
    specs: { capacity: '750ml', materials: '304 Zanglamas po‘lat' }
  },
  {
    id: 'home-kitchen-utensils',
    name: 'Silikon va yog‘och oshxona anjomlari to‘plami (12 ta)',
    brand: 'ChefSmart',
    price: 395000,
    rating: 4.9,
    reviewsCount: 168,
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Tosh qoplamali va teflon qozonlarni tirnamaydigan yuqori haroratga bardoshli silikon to‘plam.',
    specs: { weight: '1100g', temperatureRange: '-40 dan +230 °C gacha' }
  },
  {
    id: 'home-coasters',
    name: 'Finjon va choynak tagliklari (6 dona, Yog‘och)',
    brand: 'EcoKitchen',
    price: 65000,
    rating: 4.8,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Dasturxonga issiq idishlar iz qoldirishini oldini oluvchi bambuk yog‘ochli issiqlik izolyator stendlari.',
    specs: { diameter: '10 sm', materials: 'Bambuk daraxti' }
  },
  {
    id: 'home-towels',
    name: 'Mikro-tolali yumshoq yuz sochiqlari (3 tasi 1 da)',
    brand: 'SoftTouch',
    price: 95000,
    rating: 4.7,
    reviewsCount: 220,
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Suvni tez va juda yaxshi shimuvchi, yumshoqligini yo‘qotmaydigan paxtali turk sochiqlari.',
    specs: { dimensions: '50x90 sm', weight: '350g' }
  },
  {
    id: 'home-plant-deco',
    name: 'Yog‘och stendli sun’iy dekorativ mini o‘simliklar',
    brand: 'GreenOasis',
    price: 85000,
    rating: 4.5,
    reviewsCount: 164,
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Ish stoli va uydagi polkalarni bejirim ko‘rsatuvchi, umuman parvarish talab qilmaydigan dekoratsiya.',
    specs: { height: '14 sm', weight: '180g' }
  },
  {
    id: 'home-box-set',
    name: 'Kiyim va o‘yinchoqlar saqlash uchun matoli katta quti',
    brand: 'StoreMax',
    price: 125000,
    rating: 4.6,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Uy tartibini saqlashda juda asqotadigan, qopqoqli va tutqichli bukiluvchan qulay quti.',
    specs: { dimensions: '40x30x25 sm', volume: '30 Litr' }
  },
  {
    id: 'home-kitchen-scale',
    name: 'Elektron sensorli oshxona tarozisi (5 kggacha)',
    brand: 'BakerPro',
    price: 110000,
    rating: 4.8,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Shirinliklar pishirish va taomlar porsiyasini o‘lchashda taro idishi og‘irligini chiqarib hisoblovchi aniq tarozi.',
    specs: { resolution: '1g aniqlik', capacity: '5 kg', weight: '190g' }
  },
  {
    id: 'home-tea-infuser',
    name: 'Shishali chiroyli choynak (Filtrli)',
    brand: 'GlassArt',
    price: 145000,
    rating: 4.7,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Issiqqa o‘ta chidamli borosilikat shishasidan tayyorlangan, zanglamaydigan filtrli nafis choynak.',
    specs: { capacity: '900ml', weight: '310g' }
  },
  {
    id: 'home-lunchbox',
    name: 'Germetik 3-bo‘limli termos tushlik idishi (Lunchbox)',
    brand: 'HealthyBite',
    price: 115000,
    rating: 4.5,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Ishxonada yoki talabalar uchun sog‘lom ovqatlanishni ta’minlovchi, mikroto‘lqinli pechda isitiluvchan idish.',
    specs: { weight: '220g', capacity: '1200ml' }
  },
  {
    id: 'home-cushion-cover',
    name: 'Yumshoq baxmalli dekoratif yostiq jildi (2 dona)',
    brand: 'DecorStyle',
    price: 80000,
    rating: 4.7,
    reviewsCount: 104,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Yashash xonangiz divanlariga qo‘shimcha nafislik va rang go‘zalligini taratuvchi maxfiy zanjirli jildlar.',
    specs: { size: '45x45 sm', weight: '140g' }
  },
  {
    id: 'home-trash',
    name: 'Oshxona va mehmonxona uchun pedalli chelak',
    brand: 'CleanHome',
    price: 295000,
    rating: 4.6,
    reviewsCount: 47,
    image: 'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Zanglamas po‘latdan yasalgan, hid chiqarmaydigan sekin va shovqinsiz yopiluvchi qopqoqli chelak.',
    specs: { capacity: '8 Litr', weight: '1300g' }
  },
  {
    id: 'home-dispenser',
    name: 'Sensorli avtomat sovun tarqatuvchi dispenser',
    brand: 'WashPro',
    price: 210000,
    rating: 4.8,
    reviewsCount: 130,
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Qo‘lni yaqinlashtirganda avtomatik ravishda mayin ko‘pik chiqarib beruvchi teginishlarsiz datchikli dispenser.',
    specs: { battery: 'Litiy zaryadlanuvchi', reactionTime: '0.25s', weight: '240g' }
  },
  {
    id: 'home-bookmark',
    name: 'Klassik metall kitob xatchoplari (3 dona, Elegant)',
    brand: 'BookLovers',
    price: 45000,
    rating: 4.9,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Kitobxonlar uchun ajoyib dizaynerlik sovg‘asi, oltinsimon yuzali nafis metal barg ko‘rinishidagi xatchoplar.',
    specs: { weight: '15g', material: 'Guruch metal' }
  },
  {
    id: 'home-frame',
    name: 'Skandinav minimalistik foto ramka (A4 format)',
    brand: 'NordicFrame',
    price: 75000,
    rating: 4.7,
    reviewsCount: 96,
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Eng shirin xotiralaringiz va sevimli suratlaringizni devorda saqlash uchun mo‘ljallangan shishali bejirim ramka.',
    specs: { size: 'A4 format', material: 'Tabiiy daraxt silliqlangan' }
  },

  // --- BEAUTY (20 items) ---
  {
    id: 'beau-mask-1',
    name: 'Namlantiruvchi yuz niqoblari to‘plami (5 dona)',
    brand: 'OrganicFace',
    price: 65000,
    rating: 4.8,
    reviewsCount: 390,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Gialuron kislotasi va aloe sharbati bilan boyitilgan, terini charchoqdan tezda xalos etuvchi matoli niqoblar.',
    specs: { weight: '120g', skinType: 'Barcha teri turlariga mos' }
  },
  {
    id: 'beau-cream-1',
    name: 'Nafis atirli tiklovchi qo‘l kremi (Vanil va Kokos)',
    brand: 'NatureCare',
    price: 45000,
    rating: 4.7,
    reviewsCount: 232,
    image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Shea yog‘i bilan boyitilgan, quruq qo‘l terisini intensiv oziqlantiruvchi tez singuvchi krem.',
    specs: { weight: '50g', volume: '50ml' }
  },
  {
    id: 'beau-balm-1',
    name: 'Namlantiruvchi gilosli lab balzami (Gigiyenik)',
    brand: 'SweetLips',
    price: 35000,
    rating: 4.8,
    reviewsCount: 450,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Sovuq shamollarda lab burchaklari yorilishidan asrovchi tabiiy mum va vitamin E tarkibli balzam.',
    specs: { weight: '10g', scent: 'Gilos shirin atri' }
  },
  {
    id: 'beau-roller',
    name: 'Tabiiy yashil nefrit yuz massaj yo‘l-yo‘lagi (Jade Roller)',
    brand: 'ZenBeauty',
    price: 125000,
    rating: 4.6,
    reviewsCount: 74,
    image: 'https://images.unsplash.com/photo-1601049676099-e7ed07d825b0?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'ertalabki yuz shishlarini ketkazuvchi, qon aylanishini va krem singishini yaxshilovchi tabiy toshli massajyor.',
    specs: { weight: '85g', material: 'Tabiiy Yashil Nefrit' }
  },
  {
    id: 'beau-sponge',
    name: 'Professional Pardoz uchun gubka (Beauty Blender, 3 ta)',
    brand: 'MakeupArt',
    price: 55000,
    rating: 4.7,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Tonal kremlarni yuzga mukammal va tabiiy darajada silliq taratuvchi gipoallergen yumshoq gubkalar.',
    specs: { weight: '22g', material: 'Latekssiz polimer' }
  },
  {
    id: 'beau-brush-set',
    name: 'Professional bo‘yanish cho‘tkalari to‘plami (8 dona)',
    brand: 'Glossy',
    price: 195000,
    rating: 4.9,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Ko‘z, yanoq va yuz sohalari uchun sun’iy ipak tuklaridan yasalgan, mayin va sifatli cho‘tkalar dasti.',
    specs: { weight: '110g', bag: 'Maxsus charm saqlagichli' }
  },
  {
    id: 'beau-sunscreen',
    name: 'Quyoshdan himoyalovchi yengil krem SPF 50+',
    brand: 'ShieldMAX',
    price: 140000,
    rating: 4.8,
    reviewsCount: 180,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Yozning jazirama kunlarida terida pigment dog‘ paydo bo‘lishi va ultrabinafshadan asrovchi namlantiruvchi ekran.',
    specs: { volume: '50ml', protectionFactor: 'SPF 50+ PA+++' }
  },
  {
    id: 'beau-hairbrush',
    name: 'Bosh sohasini massajlovchi antistatik taroq',
    brand: 'CareHair',
    price: 75000,
    rating: 4.6,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1590156546746-c222ffef7f31?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Soch tolalari to‘kilishi va chalkashishini kamaytiruvchi, bosh terisidagi qon aylanishiga yordam beruvchi taroq.',
    specs: { weight: '75g', elements: 'Yumshoq silikon tugunchalar' }
  },
  {
    id: 'beau-scrub',
    name: 'Organik Kokos va Shakarli Tana Skrabi',
    brand: 'BodyGlow',
    price: 95000,
    rating: 4.8,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Terining o‘lik qatlamini yumshoq tozalovchi va yoshartiruvchi, shirin kokos xushbo‘yligiga ega tana silliqlovchisi.',
    specs: { capacity: '250g', materials: 'Tabiiy kokos yog‘i' }
  },
  {
    id: 'beau-aloe-gel',
    name: 'Universal 99% Aloe Vera Tinchlantiruvchi Gel',
    brand: 'BioNature',
    price: 85000,
    rating: 4.9,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Quyosh ostida yorilgan yoki qizarib achishgan terini zumda tinchlantiruvchi ko‘p funksiyali yengil gel.',
    specs: { capacity: '300ml', weight: '340g' }
  },
  {
    id: 'beau-nail-polish',
    name: 'Premium tez quruvchi nafas oluvchi tirnoq bo‘yog‘i',
    brand: 'NailStyle',
    price: 45000,
    rating: 4.5,
    reviewsCount: 56,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Tirnoq plastinkasini shikastlamaydigan, uzoq vaqt yorilmay saqlanuvchi shishasimon yorqin lak.',
    specs: { capacity: '12ml', weight: '40g' }
  },
  {
    id: 'beau-clay-mask',
    name: 'Yashil gil va choy daraxti tozalovchi yuz niqobi',
    brand: 'MatteSkin',
    price: 110000,
    rating: 4.7,
    reviewsCount: 84,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Yuzdagi qora nuqtalarni kamaytiruvchi, chuqur teshikchalarni tozalab matlashtiruvchi gil niqobi.',
    specs: { capacity: '120g', skinType: 'Yog‘li va muammoli teriga' }
  },
  {
    id: 'beau-atomizer',
    name: 'Parfyum uchun portativ mini purkovchi atomizator',
    brand: 'TravelMist',
    price: 35000,
    rating: 4.8,
    reviewsCount: 165,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Sevimli atringizni katta shishasini olib yurmasdan, doim yonda saqlash imkonini beruvchi mini purkagich.',
    specs: { capacity: '5ml', weight: '12g' }
  },
  {
    id: 'beau-bath-bomb',
    name: 'Xushbo‘y ko‘pikli dush bombalari (3 ta, To‘plam)',
    brand: 'SpaRelax',
    price: 75000,
    rating: 4.7,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Vannada dam olish va terini tinchlantirish uchun limon, lavanda va shaftoli hidli gidromassaj sovg‘alari.',
    specs: { weight: '3x100g', essence: 'Tabiiy efir yog‘lari' }
  },
  {
    id: 'beau-cotton-pads',
    name: 'Gipoallergen organik paxta drayverlari (120 dona)',
    brand: 'PureCotton',
    price: 25000,
    rating: 4.9,
    reviewsCount: 420,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Makiyajni tozalash va toniklarni qo‘llash uchun mo‘ljallangan, yuzda tuk qoldirmaydigan paxtali disklar.',
    specs: { quantity: '120 dona', material: '100% paxta tolasi' }
  },
  {
    id: 'beau-hair-clips',
    name: 'Elegant matli soch qisqichlari (Katta qisqich, 2 dona)',
    brand: 'HairGlam',
    price: 50000,
    rating: 4.6,
    reviewsCount: 104,
    image: 'https://images.unsplash.com/photo-1582234373400-3400-3400e99f0e7f?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Uylarda yoki ishda g‘oyatda qulay soch turmaklash va ushlab turish uchun mustahkam prujinali krablar.',
    specs: { weight: '36g', size: '10 sm uzunlik' }
  },
  {
    id: 'beau-eyelash-curler',
    name: 'Klassik nikel qoplamali Kiprik qayiruvchi',
    brand: 'LashUp',
    price: 45000,
    rating: 4.5,
    reviewsCount: 48,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Kipriklarni shikastlamasdan va sindirmasdan bir zumda jozibali qayrilish ulashuvchi moslama.',
    specs: { weight: '22g', elastic: 'Yumshoq silikon yostiqchali' }
  },
  {
    id: 'beau-cleanser',
    name: 'Yumshoq ko‘pikli yuz yuvish jeli (Hydra-Cleanser)',
    brand: 'WaterGlow',
    price: 115000,
    rating: 4.8,
    reviewsCount: 132,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Teridagi chang va ortiqcha yog‘ni chuqur tozalovchi, yuzni quritib tortishib qoldirmaydigan yuvish vositasi.',
    specs: { capacity: '150ml', pH: '5.5 Teri bilan muvozanat' }
  },
  {
    id: 'beau-lipmask',
    name: 'Tungi tiklovchi lab niqobi (Rezavor mevalar)',
    brand: 'BerryCare',
    price: 85000,
    rating: 4.8,
    reviewsCount: 75,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Tunda uxlash davomida quruq va yorilgan lab terisini mukammal mayinlashtiruvchi oziqlantiruvchi dori-suratma.',
    specs: { capacity: '20g', weight: '30g' }
  },
  {
    id: 'beau-mirror',
    name: 'LED yoritgichli Portativ sensorli ko‘zoynak-oyna',
    brand: 'LuxeMirror',
    price: 185000,
    rating: 4.7,
    reviewsCount: 54,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Yorqinlik darajasi bitta tegish orqali sozlanuvchi, uylarda va sayohatlarda bo‘yanishga ideal mos oyna.',
    specs: { battery: 'USB Zaryadlash', lightModes: '3 xil xira/yorqin', weight: '145g' }
  },

  // --- SPORTS (20 items) ---
  {
    id: 'spor-shaker-1',
    name: 'Zanglamas po‘latdan yasalgan Sport Shaker',
    brand: 'ActiveFit',
    price: 125000,
    rating: 4.8,
    reviewsCount: 195,
    image: 'https://images.unsplash.com/photo-1593079831268-3381b0db4a77?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Protein va sport kokteyllarini toshmasdan mukammal aralashtiruvchi metall to‘rli shaker.',
    specs: { capacity: '700ml', weight: '210g' }
  },
  {
    id: 'spor-rope-1',
    name: 'Tezkor podshipnikli professional sakrash arqoni',
    brand: 'FitRope',
    price: 75000,
    rating: 4.7,
    reviewsCount: 165,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Kardio mashg‘ulotlar davomida arqon chalkashib ketishini oldini oluvchi po‘lat simli sakragich.',
    specs: { length: '3 Metr bukiluvchi', weight: '130g' }
  },
  {
    id: 'spor-bands',
    name: 'Fitnes uchun cho‘ziluvchan rezina to‘plami (5 xil og‘irlikda)',
    brand: 'ElasticGym',
    price: 95000,
    rating: 4.9,
    reviewsCount: 380,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Uy sharoitida dumba, oyoq va qo‘l mushaklarini samarali chiniqtiruvchi lateks elastik lentalar.',
    specs: { loadRange: '4.5 dan 23 kg gacha yuklama', weight: '120g' }
  },
  {
    id: 'spor-mat',
    name: 'Sirpanmaydigan qalin yoga va fitnes mat gilamchasi',
    brand: 'ZenSport',
    price: 240000,
    rating: 4.8,
    reviewsCount: 124,
    image: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Tirsak va tizzalarga yumshatuvchi ta’sir ko‘rsatuvchi, xushbo‘y hidsiz, ekologik gilamcha.',
    specs: { thickness: '6 mm TPE material', weight: '750g' }
  },
  {
    id: 'spor-socks',
    name: 'Sport yuklamalari uchun qalin tovonli paypoqlar (3 juft)',
    brand: 'RunFree',
    price: 55000,
    rating: 4.7,
    reviewsCount: 220,
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Yugurish va sakrashda tovon qismini himoya qiluvchi elastik havotarkib sport paypoqlari.',
    specs: { weight: '80g', size: '40-44 mos' }
  },
  {
    id: 'spor-gripper',
    name: 'Og‘irligi sozlanuvchi qo‘l panja ekspanderi (Eshkak)',
    brand: 'PowerGrip',
    price: 65000,
    rating: 4.8,
    reviewsCount: 194,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Bilak va panja kuchini oshirishga yordam beruvchi, 10 dan 60 kggacha qarshilik sozlanuvchi ekspander.',
    specs: { resistance: '10 - 60 kg sozlama', weight: '135g' }
  },
  {
    id: 'spor-pouch-run',
    name: 'Yugurish uchun suvga chidamsiz bel sumkachasi',
    brand: 'RunBelt',
    price: 80000,
    rating: 4.6,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Yugurish paytida telefon, kalit va kartalarni tebranmasdan qulay saqlovchi ingichka belbog‘ sumka.',
    specs: { weight: '65g', fabric: 'Lykra elastik suv o‘tkazmas' }
  },
  {
    id: 'spor-headband',
    name: 'Ter so‘ruvchi elastik fitnes bosh bog‘ichi',
    brand: 'SweatShield',
    price: 35000,
    rating: 4.5,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Kardio mashqlar davomida peshonadan ter ko‘zlarga oqib tushishini oldini olib mahkamlovchi bog‘ich.',
    specs: { weight: '18g', material: 'Neofit material ter shimuvchi' }
  },
  {
    id: 'spor-massage-ball',
    name: 'Miofasiyal mushaklar uchun massaj to‘pi (Laxross)',
    brand: 'TriggerPoint',
    price: 50000,
    rating: 4.7,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Ishdan yoki og‘ir sport mashg‘ulotidan keyin bo‘yin va yelka mushaklarini yumshatish uchun qattiq massaj to‘p.',
    specs: { diameter: '6.3 sm', weight: '150g' }
  },
  {
    id: 'spor-gloves',
    name: 'Turnik va gantellar uchun fitnes qo‘lqoplari',
    brand: 'IronGrip',
    price: 95000,
    rating: 4.7,
    reviewsCount: 130,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Qadoqlar paydo bo‘lishi va turnikda sirpanib ketishni kamaytiruvchi yumshoq dastro‘molli yarim-qo‘lqoplar.',
    specs: { weight: '55g', size: 'M va L o‘lchamlar' }
  },
  {
    id: 'spor-bottle',
    name: 'Ekologik Tritan materialidan tayyorlangan Suv idishi',
    brand: 'EcoHydro',
    price: 110000,
    rating: 4.8,
    reviewsCount: 175,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Zarbali tushishlarga o‘ta bardoshli, sog‘liq uchun mutlaqo xavfsiz BPA-free suv butilkasi.',
    specs: { capacity: '1000ml', weight: '140g' }
  },
  {
    id: 'spor-towels-gym',
    name: 'Tez quriydigan engil mikro-tolali sport sochiq',
    brand: 'DryFit',
    price: 65000,
    rating: 4.8,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Trenajor zalida trenajorlar ustiga qo‘yish va ter artish uchun o‘ta ixcham bukiluvchan sochiq.',
    specs: { size: '40x80 sm', weight: '60g' }
  },
  {
    id: 'spor-armband',
    name: 'Yuguruvchilar uchun qo‘lga taqiladigan telefon sumkasi',
    brand: 'PhoneTrack',
    price: 75000,
    rating: 4.6,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'bilak yoki yelkaga mahkamlanadigan, musiqa eshitish uchun qulay sim teshiklik sensorli g‘ilof sumka.',
    specs: { weight: '45g', screenCompatible: '6.7 dyuymlik telefonlargacha' }
  },
  {
    id: 'spor-pushup-bars',
    name: 'Otjimaniya (Tayanib tortilish) uchun metall tutqichlar',
    brand: 'PushUpPro',
    price: 165000,
    rating: 4.7,
    reviewsCount: 74,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Bileklarni ortiqcha og‘riq va zriqishlardan saqlovchi, chuqurroq egilish imkonini beruvchi sement pol tutgichlar.',
    specs: { weight: '540g', base: 'Keng sirpanmaydigan oyoqlar' }
  },
  {
    id: 'spor-goggles',
    name: 'Suv ostida suzish uchun tumanlanmaydigan ko‘zoynak',
    brand: 'SwimAero',
    price: 135000,
    rating: 4.8,
    reviewsCount: 93,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Anti-fog tumanlanishga qarshi qoplamali va suv o‘tkazmaydigan silikon halqali universal sport ko‘zoynagi.',
    specs: { weight: '65g', protection: 'UV protection + Anti-fog' }
  },
  {
    id: 'spor-gymbag',
    name: 'Katta sig‘imli sport sumkasi (Poyabzal bo‘limi bilan)',
    brand: 'ActiveGym',
    price: 295000,
    rating: 4.8,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Kastyumlar va alohida krossovka bo‘lmasi tufayli kiyimlarni toza saqlovchi mukammal sportiv sayohat sumkasi.',
    specs: { weight: '480g', volume: '32 Litr' }
  },
  {
    id: 'spor-ankle-weights',
    name: 'Oyoq va qo‘l uchun maxsus qumli og‘irlashtirgichlar (2x1kg)',
    brand: 'PowerWeights',
    price: 120000,
    rating: 4.6,
    reviewsCount: 54,
    image: 'https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Mashg‘ulot poygalari davomida oyoq va son yuklamalarini kuchaytiruvchi keng yopishqoqli og‘irlashtirgichlar.',
    specs: { weight: '2 x 1 kg', filling: 'Kvarsit qum zarralari' }
  },
  {
    id: 'spor-exercise-ball',
    name: 'Katta gimnastika va fitbol koptoki (Nasos bilan)',
    brand: 'GymBall',
    price: 185000,
    rating: 4.7,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Xavfsiz portlamaydigan texnologiya (Anti-Burst), homiladorlar va umurtqa pog‘onasi mashqlari uchun ideal sherik.',
    specs: { diameter: '65 sm', weight: '900g', capacity: '150kg gacha' }
  },
  {
    id: 'spor-knee-support',
    name: 'Ergo-Kompressor sport tizza himoyalovchi ortez',
    brand: 'KneeGuard',
    price: 95000,
    rating: 4.5,
    reviewsCount: 115,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Og‘ir toshlar ko‘targanda yoki yugurganda tizza bo‘g‘imlarini fiksatsiya qilib, jarohatlanishdan saqlovchi bandaj.',
    specs: { weight: '85g', fabric: 'Neylon va elastan' }
  },
  {
    id: 'spor-wheel',
    name: 'Qorin matbuoti (Press) uchun ikki g‘ildirakli rolik',
    brand: 'CoreWheel',
    price: 135000,
    rating: 4.8,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Qorin press sohalari, elka, bel va qomatni chiniqtirish uchun metal o‘zakli va yumshoq sirpanmaydigan oyoq matli rolik.',
    specs: { weight: '650g', wheels: 'Ikki tomonlama barqaror' }
  },

  // --- LUXURY PRE-EXISTING PRODUCTS ADAPTED UNDER 800,000 SO'M ---
  {
    id: 'studio-pro-x1',
    name: 'Studio Pro X1 Simsiz Quloqchin',
    brand: 'SONUS',
    price: 690000,
    rating: 4.8,
    reviewsCount: 84,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEaGaHx8YjKiVj6E3j7lxMVnqHAWSwAaXA-f3pKw6jpoId4_V34-jYXPU1_xTQPHq7FQwpJBbb6zIbw0OVHM8Fx8rHoW7PYjyvGhKU2b0z_o0KOfufWkIU5WRFzh82VaLZdvEMapehT7o1Zm_khusnEqSLPohwWO6Gr1-W61c32mX2Yk8WfvOFUVB1RCGPRI7hZlfE2yMN6WH3HLfetmmx-SqVGALlV6ymFzZ3SNy9TnmcEfGw1dDul8B-oxZlzOxnTdjgAj1vUC3F',
    category: 'electronics',
    description: 'Yuqori aniqlikdagi audio chiqish va faol shovqin blokirovkalari uchun mo‘ljallangan o‘ta bejirim professional akustik quloqchin.',
    specs: { battery: '40 Soat', isolation: 'Faol Shovqin Bloklash (ANC)', range: '15 Metr (Bluetooth 5.3)', weight: '270g' }
  },
  {
    id: 'luna-chrono',
    name: 'Luna Chrono Klassik Charm Soat',
    brand: 'HORIZON',
    price: 520000,
    rating: 4.6,
    reviewsCount: 42,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5veSc6DQ8tMMnGq_C-UKN93MQn59O-hnvY5UUWKhaWwYhIluJvQQwHFqdV7P-tBcWsRBIHyl9l7T_sqmKIuActL8b4QLdFvwQdNvezvAXpzGH4QuadkMHQoxMoasVC9bpjETmCmLn5HqgSr4mJzhHr1_OXomU5gjQwn94kp4XUP1KUAWJ_WFHPGxQhFZjrWUa7UWy6e6-S8P0kK5NkDla8V4TFefTi4jedSKDHIsv_t1wheh_Wfxv3KYML2cAP4rXMRevqiuj75d4',
    category: 'fashion',
    description: 'minimalistik va nafis Shvetsariya uslubidagi qo‘l soati. Chidamli karkas va tabiiy qo‘lda ishlangan charm uzmalar.',
    specs: { battery: '12 Oy', isolation: '3 ATM Suvga Chidamlilik', weight: '62g' }
  },
  {
    id: 'opal-desk-light',
    name: 'Opal Touch Smart Stol Chirog‘i',
    brand: 'OPAL',
    price: 290000,
    rating: 4.7,
    reviewsCount: 56,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvHGah4EFhCaxFJ34u-vEx2G7Om8luw1eApLSsJeMP808VnwowdebOs3cZoOOaKpfou2CQ9LHnUEksSoKAe0SYFUCF1sl_s6_7XX_8xd15NlhTnd-iaqpC_dcFQnjYV0s0hcjXc6XbtaDEvEpzaU7YMN9TOpcbiLTzecGmp6jW1eBUQ4tdxlQtfTjCE-C7WVkSe5fS_OxXQi3JwmFU1Gd6-UnEoXIUobW1EaBQXZNONJyHBl3fpwY2NOg5RyoDOFLBcPLsh8MDFcjW',
    category: 'home',
    description: 'Ish stolingiz yoki yotoqxonangiz uchun ko‘z xiralashuvini kamaytiruvchi ko‘p rejimli LED chiroq.',
    specs: { isolation: 'Ikki xil yorqinlik sadosi', weight: '1200g' }
  },
  {
    id: 'velocity-runner',
    name: 'Velocity Ultra-Yengil Krossovka',
    brand: 'VELOCITY',
    price: 495000,
    rating: 4.5,
    reviewsCount: 93,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWBo_ZkGTArM8ueR6RW3xqVGOamJ1cPBxuP0AH5BrzKL4QkGMX2Djg6ij7nG27Pl2XyrpFpFlcsxuhLJWnixmzF68MIXa6WxZ4pnkWUiCNcNMPYRIFuUvW9oJT3Els4dEdJ6XDmR3hH5USgiycEOajE-ExHA5Ht-7k-Cm79WMIDKxHm1btK25J_IGY2CLIB9iGwP68uSmmYK04gCZmOnxKGM0RkzqPJB5lFh-FR8U93hlVManrwBG7_S-Xwev7OtyJRXHBTfGQQrkV',
    category: 'sports',
    description: 'Ortopedik yumshoq ko‘pikli taglik bilan yugurish va fitnesga mo‘ljallangan sport krossovkasi.',
    specs: { weight: '235g', isolation: 'Tovonni Himoyalash Tizimi' }
  },
  {
    id: 'onyx-chrono',
    name: 'Onyx Chrono Hashamatli Qora Soat',
    brand: 'HORIZON',
    price: 760000,
    rating: 4.9,
    reviewsCount: 112,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_s6FNhJYRxymmc8zxwfikoISj0kXgvPks6U8mqSBHhC_sZbBPEI-gCGFUBWOVKITmURkS8GoyFcPNRHT9Q2oC0C-yLRJcrrbnIvRA4D2t5vZ8oUn2xRiHyYCKSX5NLbox8vr9AvuyHWTa3aq_rw2G7bv14ehDPsIHUOgBE1OxZElzcE6UA5Z4AExc1IIRC8zp3VMR6ccD_17x22DUN0yOszJGYDQMb6lV0rTiGyKzkMvSZ9mlDFdJPSaKTU_8kv5tTuRELHJTdfeH',
    category: 'fashion',
    description: 'Muhtasham qora metall korpus va premium dizaynni mujassamlashtirgan mukammal soat.',
    specs: { battery: '24 Oy', isolation: '5 ATM Suv o‘tkazmas', weight: '75g' }
  },
  {
    id: 'aero-runner',
    name: 'Aero Runner Moviy Sport Krossovka',
    brand: 'VELOCITY',
    price: 490000,
    rating: 4.7,
    reviewsCount: 65,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnwEnaqUQfIBJkSba2C4rYLXgzpU7WHgbYcbz-xTSe5Mk2F6mGhJpMRvP3IBubIZGd4RkmzoSQ8Sk3QufyDKUwsT4FpdaEVMefmA_x9Cq0sxaA1iA1atT73220M95ImkaN8MKGhdZN9iBYFevdfd02KKRd90k_HOSuB6rf8dlf_IHphNfXFGgTJj6pgSaRbcMkqzruORNZJ2F_6xDQxM4hEAB49fE0uhTzf_9HLo4UkrggzzrOdCszKhZLW5LWLbqRZiyLnuyAA1Sv',
    category: 'sports',
    description: 'Havo aylanuvchi to‘rli AeroBreathe poyabzali, harakatlar erkinligi va yengillik uchun yaratilgan.',
    specs: { weight: '210g', isolation: 'AeroBreathe Yengil To‘r' }
  },
  {
    id: 'nordic-mist',
    name: 'Nordic Mist Premium Atir',
    brand: 'ESSENCE',
    price: 385000,
    rating: 4.4,
    reviewsCount: 38,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByRolG6h9kNjuuJl4UZqisGGfhWel-2NTJeDDfXr8Z4ECdsNJdpYdky0MHJ9lXwVAN9ueXe3daX3nz6B5yBoyrJIsaEzJGFTP9UuY7BGxOC-BIvv5_Bf2n3waJKo2at52FuJwFxeDh-ZhRnDtoy7Fn33HZlvgWYrAcRSllNlRe3tOTGqq2fxVZjAkx63PGJVKPZcWdVTrAme6kp_x99nsC9l_pfthTI4CYmX2hHgIhcmq2cXb3pab8HYoNVBh0AEgj36dK_jhewzAM',
    category: 'beauty',
    description: 'Tog‘ o‘rmonlariga uyg‘un tushgan toza okean ifori. Sizga kun davomida yangilik va yoqimli aura taqdim etuvchi premium hid.',
    specs: { weight: '100ml', isolation: 'Uzun shleyf ifori (EDP)' }
  }
];
