import { Product } from './types';

export const CATEGORIES = [
  { id: 'electronics', name: 'Electronics', icon: 'devices' },
  { id: 'fashion', name: 'Fashion', icon: 'apparel' },
  { id: 'home', name: 'Home', icon: 'home' },
  { id: 'beauty', name: 'Beauty', icon: 'auto_awesome' },
  { id: 'sports', name: 'Sports', icon: 'fitness_center' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'studio-pro-x1',
    name: 'Studio Pro X1',
    brand: 'SONUS',
    price: 299.00,
    rating: 4.8,
    reviewsCount: 84,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEaGaHx8YjKiVj6E3j7lxMVnqHAWSwAaXA-f3pKw6jpoId4_V34-jYXPU1_xTQPHq7FQwpJBbb6zIbw0OVHM8Fx8rHoW7PYjyvGhKU2b0z_o0KOfufWkIU5WRFzh82VaLZdvEMapehT7o1Zm_khusnEqSLPohwWO6Gr1-W61c32mX2Yk8WfvOFUVB1RCGPRI7hZlfE2yMN6WH3HLfetmmx-SqVGALlV6ymFzZ3SNy9TnmcEfGw1dDul8B-oxZlzOxnTdjgAj1vUC3F',
    category: 'electronics',
    description: 'Experience professional acoustic performance with custom-tuned dynamic drivers, engineered for high-fidelity audio output and active isolation.',
    specs: {
      battery: '40 Hours',
      isolation: 'ANC Medium',
      range: '40 Feet',
      latency: 'Standard',
      weight: '270g',
      frequencyResponse: '20Hz - 20kHz',
      driverDiameter: '40 mm',
      charging: 'USB-C Cable',
    }
  },
  {
    id: 'luna-chrono',
    name: 'Luna Chrono',
    brand: 'HORIZON',
    price: 185.00,
    rating: 4.6,
    reviewsCount: 42,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5veSc6DQ8tMMnGq_C-UKN93MQn59O-hnvY5UUWKhaWwYhIluJvQQwHFqdV7P-tBcWsRBIHyl9l7T_sqmKIuActL8b4QLdFvwQdNvezvAXpzGH4QuadkMHQoxMoasVC9bpjETmCmLn5HqgSr4mJzhHr1_OXomU5gjQwn94kp4XUP1KUAWJ_WFHPGxQhFZjrWUa7UWy6e6-S8P0kK5NkDla8V4TFefTi4jedSKDHIsv_t1wheh_Wfxv3KYML2cAP4rXMRevqiuj75d4',
    category: 'fashion',
    description: 'A modern minimalist timepiece honoring the Swiss heritage of clarity and premium craftsmanship. Features a durable sapphire crystal dial and genuine hand-stitched leather strap.',
    specs: {
      battery: '12 Months',
      isolation: '3 ATM Water Resist',
      range: 'N/A',
      latency: 'Instant Swiss',
      weight: '62g',
      frequencyResponse: 'Analog Quartz',
      driverDiameter: '38 mm',
      charging: 'Button Cell',
    }
  },
  {
    id: 'opal-desk-light',
    name: 'Opal Desk Light',
    brand: 'OPAL',
    price: 120.00,
    rating: 4.7,
    reviewsCount: 56,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvHGah4EFhCaxFJ34u-vEx2G7Om8luw1eApLSsJeMP808VnwowdebOs3cZoOOaKpfou2CQ9LHnUEksSoKAe0SYFUCF1sl_s6_7XX_8xd15NlhTnd-iaqpC_dcFQnjYV0s0hcjXc6XbtaDEvEpzaU7YMN9TOpcbiLTzecGmp6jW1eBUQ4tdxlQtfTjCE-C7WVkSe5fS_OxXQi3JwmFU1Gd6-UnEoXIUobW1EaBQXZNONJyHBl3fpwY2NOg5RyoDOFLBcPLsh8MDFcjW',
    category: 'home',
    description: 'A designer ceramic desk lamp with a smooth matte finish, designed for bright ambient workspaces. Simulates gentle natural sunlight for stress-free eye comfort.',
    specs: {
      battery: 'N/A (Plugged)',
      isolation: 'Dual Hue Warm/Cool',
      range: 'Standard Cord',
      latency: 'Instant-on',
      weight: '1200g',
      frequencyResponse: '60Hz flicker-free',
      driverDiameter: 'LED Panel 120mm',
      charging: 'Wall adapter',
    }
  },
  {
    id: 'velocity-runner',
    name: 'Velocity Runner',
    brand: 'VELOCITY',
    price: 145.00,
    rating: 4.5,
    reviewsCount: 93,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWBo_ZkGTArM8ueR6RW3xqVGOamJ1cPBxuP0AH5BrzKL4QkGMX2Djg6ij7nG27Pl2XyrpFpFlcsxuhLJWnixmzF68MIXa6WxZ4pnkWUiCNcNMPYRIFuUvW9oJT3Els4dEdJ6XDmR3hH5USgiycEOajE-ExHA5Ht-7k-Cm79WMIDKxHm1btK25J_IGY2CLIB9iGwP68uSmmYK04gCZmOnxKGM0RkzqPJB5lFh-FR8U93hlVManrwBG7_S-Xwev7OtyJRXHBTfGQQrkV',
    category: 'sports',
    description: 'High-performance running sneakers incorporating responsive foam sole structure and breathable hyper-knit fabric wrapper for explosive energetic bounce.',
    specs: {
      battery: 'N/A',
      isolation: 'Heel-Lock Tech',
      range: 'All Terrain',
      latency: 'High Energy',
      weight: '235g',
      frequencyResponse: 'Impact Absorb',
      driverDiameter: 'Responsive Foam',
      charging: 'N/A',
    }
  },
  {
    id: 'onyx-chrono',
    name: 'Onyx Chrono',
    brand: 'HORIZON',
    price: 295.00,
    rating: 4.9,
    reviewsCount: 112,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_s6FNhJYRxymmc8zxwfikoISj0kXgvPks6U8mqSBHhC_sZbBPEI-gCGFUBWOVKITmURkS8GoyFcPNRHT9Q2oC0C-yLRJcrrbnIvRA4D2t5vZ8oUn2xRiHyYCKSX5NLbox8vr9AvuyHWTa3aq_rw2G7bv14ehDPsIHUOgBE1OxZElzcE6UA5Z4AExc1IIRC8zp3VMR6ccD_17x22DUN0yOszJGYDQMb6lV0rTiGyKzkMvSZ9mlDFdJPSaKTU_8kv5tTuRELHJTdfeH',
    category: 'fashion',
    description: 'Uncompromising prestige black-out wristware configured with genuine top-grain calfskin leather and precision flyback stopwatch dials. Elegantly robust.',
    specs: {
      battery: '24 Months',
      isolation: '5 ATM Water Resist',
      range: 'N/A',
      latency: 'Precision Flyback',
      weight: '75g',
      frequencyResponse: 'Quartz Japanese',
      driverDiameter: '42 mm',
      charging: 'Silver-oxide Cell',
    }
  },
  {
    id: 'aero-runner',
    name: 'Aero Runner',
    brand: 'VELOCITY',
    price: 180.00,
    rating: 4.7,
    reviewsCount: 65,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnwEnaqUQfIBJkSba2C4rYLXgzpU7WHgbYcbz-xTSe5Mk2F6mGhJpMRvP3IBubIZGd4RkmzoSQ8Sk3QufyDKUwsT4FpdaEVMefmA_x9Cq0sxaA1iA1atT73220M95ImkaN8MKGhdZN9iBYFevdfd02KKRd90k_HOSuB6rf8dlf_IHphNfXFGgTJj6pgSaRbcMkqzruORNZJ2F_6xDQxM4hEAB49fE0uhTzf_9HLo4UkrggzzrOdCszKhZLW5LWLbqRZiyLnuyAA1Sv',
    category: 'sports',
    description: 'Striking electric-blue trainers engineered for elite endurance track runs. Soft box layout ensures minimal friction with maximal ventilation.',
    specs: {
      battery: 'N/A',
      isolation: 'AeroBreathe Mesh',
      range: 'Track & Field',
      latency: 'Ultralight Sole',
      weight: '210g',
      frequencyResponse: 'Dynamic Spring',
      driverDiameter: 'Air Cushion',
      charging: 'N/A',
    }
  },
  {
    id: 'pure-audio-ii',
    name: 'Pure Audio II',
    brand: 'SONUS',
    price: 450.00,
    rating: 4.9,
    reviewsCount: 204,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgHSX_v_If7sjxq7lP4XaUvMUaw64TNL-dqgUkIDAzHrcaOwEjdIku_h3g8RHh9_nKwjIOJrMVusL5RU-urK4gz_WXriOLASCgi8tvO_BDC5HV0Ar8q4pP8kPE4DaJgq9jZx0YCyS5glEnx08XNiD0v0pmbK1OYuQUZXarcL7wDwB02IQbX77iwcoNjq_KeZVAlv-bSPAVLHgirTFzJgTSmieU34CKrpQQig-Mlw0W1eTJM_z6kOihvxhfuVkzC6khmUvw7nx_KT3X',
    category: 'electronics',
    description: 'Audiophile grade titanium over-ear sound transducers. Delivers pure atmospheric studio response with hyper-realistic instrument spatial layouts.',
    specs: {
      battery: '50 Hours',
      isolation: 'Closed Back Passive',
      range: 'Wireless & Corded',
      latency: 'Low Latency aptX',
      weight: '310g',
      frequencyResponse: '5Hz - 42kHz',
      driverDiameter: '50 mm',
      charging: 'USB-C SuperCharge',
    }
  },
  {
    id: 'nordic-mist',
    name: 'Nordic Mist',
    brand: 'ESSENCE',
    price: 120.00,
    rating: 4.4,
    reviewsCount: 38,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByRolG6h9kNjuuJl4UZqisGGfhWel-2NTJeDDfXr8Z4ECdsNJdpYdky0MHJ9lXwVAN9ueXe3daX3nz6B5yBoyrJIsaEzJGFTP9UuY7BGxOC-BIvv5_Bf2n3waJKo2at52FuJwFxeDh-ZhRnDtoy7Fn33HZlvgWYrAcRSllNlRe3tOTGqq2fxVZjAkx63PGJVKPZcWdVTrAme6kp_x99nsC9l_pfthTI4CYmX2hHgIhcmq2cXb3pab8HYoNVBh0AEgj36dK_jhewzAM',
    category: 'beauty',
    description: 'Delicate forest pine scent layered on pure glacial ocean breeze, encased beautifully within weighted modern glassware with heavy metallic top caps.',
    specs: {
      battery: 'N/A',
      isolation: 'Concentrated EDC',
      range: 'Long Lasting 8h',
      latency: 'Soft Sillage',
      weight: '100ml',
      frequencyResponse: 'Fragrance Profile',
      driverDiameter: 'Mist Atomizer',
      charging: 'Re-fillable',
    }
  },
  {
    id: 'tab-pro-x',
    name: 'Tab Pro X',
    brand: 'CORE',
    price: 899.00,
    rating: 4.8,
    reviewsCount: 152,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDqVcm2tYHn7BJwFWmQy9qx0Pe3xE3hibWuxHz0BHp_E4GbidH-_5R6K2ndm3fdTif6b3vKXhOZtxpu0iYbls5RJIHv2OeuSHuedXh1kD6ju7itV4bC2j1IPv9VWsv_NGtInb9Uv4rvL6FmGV0KbiTjpHfY6ssKarR0-5YKeeku15l5sGzZNPAFNd5dC5F3Vej247jvBTJ1e3uulieNmncvM9gXEj7U9KDsmhCb887Tus5IJSkpgfGckrnfJhKw_ZQtPW2lDmuN2I4m',
    category: 'electronics',
    description: 'An ultra-compact high-brightness designer productivity slate, supporting smooth multi-panel flows, accurate active stylet input tracking, and deep ambient sound system.',
    specs: {
      battery: '16 Hours',
      isolation: 'HDR10+ AMOLED',
      range: 'Wi-Fi 6E & 5G',
      latency: '120Hz Refresh',
      weight: '495g',
      frequencyResponse: 'Quad Atmos Speakers',
      driverDiameter: '11 inch Display',
      charging: 'USB-C 45W',
    }
  },
  {
    id: 'shadow-elite',
    name: 'Shadow Elite',
    brand: 'APEX',
    price: 210.00,
    rating: 4.8,
    reviewsCount: 77,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZAe_naQ6g4YsGa8gMzFtYO5dar6wyrMgo_zVjdc_L7WgVPTF0W2ZCjfKC7HQ4snkrEkKmRjHGjTqvUp4bE8RRxHhAAtsz1dChd15816sArRpWifd0b_aNNCbeuzDc4RAoqo9roSiB260PyPETzf91wp3STvAAWlBf_aNm_3iy0OYPYvC5dfmQrfmvsKnRuE58j3wX7P2RAPnPqhICLkZsx845s3dEjiYtoZmeXTbWFank-bgochxfn-kOYdhHaAFyuIOmGwGeOoSr',
    category: 'sports',
    description: 'Carbon fiber plate running shoes configured to shave precious seconds off your marathon target. Advanced high-bounce rubber heel rings provide responsive control.',
    specs: {
      battery: 'N/A',
      isolation: 'Carbon SpeedPlate',
      range: 'Road Marathon',
      latency: 'Ultra Responsive',
      weight: '195g',
      frequencyResponse: 'Traction Grip',
      driverDiameter: 'Energy Foam v2',
      charging: 'N/A',
    }
  },
  {
    id: 'apex-ultra-wireless',
    name: 'Apex Ultra Wireless',
    brand: 'APEX',
    price: 349.00,
    rating: 4.5,
    reviewsCount: 128,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBud-aefsBrsWBKhb2-Gmk8UL5UI8d-DM5KV09t9tLXoV7h4cZV2xwTOR6ikms20HylIc488bat-_5V03JpteV-FmHErkeUvKbawKo4RgZTg_aHboCS3gcnhbS3pCSDJMMzvjH_o6k0_55h6mQE4hR_abhXPLn1Nzp61rGZLetwHtgY9vDhBDqlRpU8Hy61TiU2Ax8qI0iGqQXxIw-k9ZJPyfjDpc8sy1m2m9uFwsV23u_F3Tga4Gv6yCTqsgcWwc3WBWqOAdb4RXW5',
    category: 'electronics',
    description: 'Engineered for those who demand acoustic perfection. The Apex Ultra features custom-tuned 40mm drivers and industry-leading noise cancellation technology, creating a sanctuary of sound even in the most chaotic environments. Crafted with memory foam and protein leather for all-day comfort.',
    specs: {
      battery: '60 Hours',
      isolation: 'ANC Max',
      range: '50 Feet',
      latency: 'Ultra Low',
      weight: '250g',
      frequencyResponse: '5Hz - 40kHz',
      driverDiameter: '40 mm',
      charging: 'USB-C Fast Charge',
    },
    additionalImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBud-aefsBrsWBKhb2-Gmk8UL5UI8d-DM5KV09t9tLXoV7h4cZV2xwTOR6ikms20HylIc488bat-_5V03JpteV-FmHErkeUvKbawKo4RgZTg_aHboCS3gcnhbS3pCSDJMMzvjH_o6k0_55h6mQE4hR_abhXPLn1Nzp61rGZLetwHtgY9vDhBDqlRpU8Hy61TiU2Ax8qI0iGqQXxIw-k9ZJPyfjDpc8sy1m2m9uFwsV23u_F3Tga4Gv6yCTqsgcWwc3WBWqOAdb4RXW5',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBv9zBBj41taJqrwt1LQAHM_jQk3Fd9ghuBGXArxuhColmK8SnPbnqqvNOOWiV243Acz0SfR6PRyqBxJ9yyPyISb5ejsrWyXKn5xrU5Ne5VPmWsmwCxzUKhdziv_OM1HYJUg0EW1nWYsK9dm1LspLVC-oVMpKldvvlPFirMJpWYLXW7UoYzCvypn8SnX04Y7ZAOs5RmOXGhdzWf51Yd9W9E3Vve9rN-aSYRWJxQLWmAB4KHGUZ2VYK7yELH721cv7lg7tYrZhGIRgw_'
    ]
  },
  {
    id: 'velocity-pro-runner',
    name: 'Velocity Pro-Runner',
    brand: 'VELOCITY',
    price: 180.00,
    rating: 4.6,
    reviewsCount: 78,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCEN_ZUkunDwbb4Eai6eFldv2pUeVKqv5N4HesABnkGp-h4JIss9AhVWWQRryXGhO2IEa6gMdyYjLYs-JVIGQHlRLxXMJuAPK_eavAwokF-rPEaPuMagQlyRSVMT3NG7lkM5hJmEeWvCyp87PPRDPexcO_Gq1iMZhlzu_MIwl2c0VVhkNMOh4xu9KoZQNKQgehoD2XWPzkY5j2_o4ebpkOpahHQ1PQx-c9Jz17I3iEC9yQ91fDeSw5ag9rjRRH7-hIeTVbo-3rox8U',
    category: 'sports',
    description: 'A professional premium electric blue runner. Styled seamlessly for maximum road endurance and stylish off-court presence.',
    specs: {
      battery: 'N/A',
      isolation: 'Stable Heel Support',
      range: 'All Terrain',
      latency: 'Lightweight Bounce',
      weight: '240g',
      frequencyResponse: 'Shock Absorption',
      driverDiameter: 'Active Foam Extra',
      charging: 'N/A',
    }
  },
  {
    id: 'luxe-chrono-white',
    name: 'Luxe Chrono White',
    brand: 'HORIZON',
    price: 350.00,
    rating: 4.8,
    reviewsCount: 121,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVFcfGtkLgYguIIwSvPgo5Dyft14CiZuo49THke4LSwityzptSIO5T-cLpaEdL8xibeXSzkrcZqwakoinFew3WfxPrwQuKEXTbvjRzaUd52bdUCBD4qJjFvyt4aBjWGrk7G96SxICAeXX1_fNZEjwn7Z0_3OgN626w0cbGE9G1VHCUcJEkzoCEQactaD3rQBjJKGftRQ-XtZpJSb0jIpVOYrNRhb8q7xANas4LWT88F_vixnSZO0kE_KCeN9d4COT4CclIdSxTqpl2',
    category: 'fashion',
    description: 'An elegant high-key white smart timepiece designed with a pristine polished casing, continuous heart activity sensor, and long-life battery cell.',
    specs: {
      battery: '7 Days Active',
      isolation: 'IP68 Swim-proof',
      range: 'BT 5.2 Secure',
      latency: 'Haptic Crown',
      weight: '55g',
      frequencyResponse: 'AMOLED Always-On',
      driverDiameter: '40 mm Dial',
      charging: 'Magnetic Puck',
    }
  },
  {
    id: 'acoustics-ultra-x',
    name: 'Acoustics Ultra X',
    brand: 'SONUS',
    price: 299.00,
    rating: 4.7,
    reviewsCount: 89,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAIlBoEmlDaffF029v3_Zdnz4iaiGAt6UNy942g5ptdeOEbq3nGIBPQP89OJrOfOB0INrN29Sfo1LcRQuMyf0UsoO99I8xAcuDV45w-WR18Ic98mZGsiWEaTEfCkQBpbmmYdr4ffjG4beJ53hegCcvrVKB7Ivgte-3pA1eKx9N_D2kd2G8xi9yv3lxpd_d_2xtGFihBv-cAVmAU3Z3cBbAw6e8at9LaZklSBeTYu_fsAmYXvA_v9YjLULbSPJizKCYt6loRWPv9haHX',
    category: 'electronics',
    description: 'Premium high-comfort noise canceling headphones designed for long audio mastering sessions, finished in a textured matte carbon texture with custom padded headband.',
    specs: {
      battery: '45 Hours',
      isolation: 'Advanced Hybrid ANC',
      range: '45 Feet',
      latency: 'Acoustic Zero-lag',
      weight: '265g',
      frequencyResponse: '10Hz - 35kHz',
      driverDiameter: '40 mm Custom',
      charging: 'USB-C Fast Charge',
    }
  },
  {
    id: 'aurora-skin-regenerator',
    name: 'Aurora Laser Wand',
    brand: 'ESSENCE',
    price: 380.00,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvHGah4EFhCaxFJ34u-vEx2G7Om8luw1eApLSsJeMP808VnwowdebOs3cZoOOaKpfou2CQ9LHnUEksSoKAe0SYFUCF1sl_s6_7XX_8xd15NlhTnd-iaqpC_dcFQnjYV0s0hcjXc6XbtaDEvEpzaU7YMN9TOpcbiLTzecGmp6jW1eBUQ4tdxlQtfTjCE-C7WVkSe5fS_OxXQi3JwmFU1Gd6-UnEoXIUobW1EaBQXZNONJyHBl3fpwY2NOg5RyoDOFLBcPLsh8MDFcjW',
    category: 'beauty',
    description: 'Advanced medical-grade micro-current and red-light wand designed to restore skin vigor, smoothen wrinkles, and offer natural spa-level lifting at home.',
    specs: {
      battery: '3 Hours Continuous',
      isolation: 'Hypoallergenic Titanium',
      range: 'USB Wireless Charging Base',
      latency: 'Instant Radiant Output',
      weight: '85g',
      frequencyResponse: '630nm Wave Length',
      driverDiameter: '360° Rotating Head',
      charging: 'Magnetic Wireless Stand',
    }
  },
  {
    id: 'luna-gold-necklace',
    name: '24K Solstice Chain',
    brand: 'HORIZON',
    price: 750.00,
    rating: 5.0,
    reviewsCount: 31,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEaGaHx8YjKiVj6E3j7lxMVnqHAWSwAaXA-f3pKw6jpoId4_V34-jYXPU1_xTQPHq7FQwpJBbb6zIbw0OVHM8Fx8rHoW7PYjyvGhKU2b0z_o0KOfufWkIU5WRFzh82VaLZdvEMapehT7o1Zm_khusnEqSLPohwWO6Gr1-W61c32mX2Yk8WfvOFUVB1RCGPRI7hZlfE2yMN6WH3HLfetmmx-SqVGALlV6ymFzZ3SNy9TnmcEfGw1dDul8B-oxZlzOxnTdjgAj1vUC3F',
    category: 'fashion',
    description: 'Expertly forged hand-crafted 24K pure gold necklace featuring a classic woven chain link system and single brilliant ethically-sourced diamond accent.',
    specs: {
      battery: 'Eternal Lifetime',
      isolation: 'Water/Heat Resistant',
      range: 'Length: 22 inches',
      latency: 'Master Craftsman Forged',
      weight: '45g Pure Gold',
      frequencyResponse: 'Brilliant Diamond Cut',
      driverDiameter: '5 mm width',
      charging: 'No Charging Required',
    }
  },
  {
    id: 'zenith-smart-mat',
    name: 'Zenith Interactive Yoga Mat',
    brand: 'VELOCITY',
    price: 245.00,
    rating: 4.8,
    reviewsCount: 54,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWBo_ZkGTArM8ueR6RW3xqVGOamJ1cPBxuP0AH5BrzKL4QkGMX2Djg6ij7nG27Pl2XyrpFpFlcsxuhLJWnixmzF68MIXa6WxZ4pnkWUiCNcNMPYRIFuUvW9oJT3Els4dEdJ6XDmR3hH5USgiycEOajE-ExHA5Ht-7k-Cm79WMIDKxHm1btK25J_IGY2CLIB9iGwP68uSmmYK04gCZmOnxKGM0RkzqPJB5lFh-FR8U93hlVManrwBG7_S-Xwev7OtyJRXHBTfGQQrkV',
    category: 'sports',
    description: 'Smart exercise pad configured with pressure-sensitive haptic sensors and guiding LED light indicators for flawless pose correction and balanced flow.',
    specs: {
      battery: '12 Hours Usage',
      isolation: 'Shock-absorbing Grip Base',
      range: 'BT 5.1 App Sync',
      latency: 'Real-time Positional Feed',
      weight: '1600g',
      frequencyResponse: 'Pressure Grid Dynamic',
      driverDiameter: '72 x 24 inches',
      charging: 'USB-C Cable',
    }
  },
  {
    id: 'levitate-ambient-sound',
    name: 'Levitate Floating Orb',
    brand: 'SONUS',
    price: 599.00,
    rating: 4.9,
    reviewsCount: 68,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_s6FNhJYRxymmc8zxwfikoISj0kXgvPks6U8mqSBHhC_sZbBPEI-gCGFUBWOVKITmURkS8GoyFcPNRHT9Q2oC0C-yLRJcrrbnIvRA4D2t5vZ8oUn2xRiHyYCKSX5NLbox8vr9AvuyHWTa3aq_rw2G7bv14ehDPsIHUOgBE1OxZElzcE6UA5Z4AExc1IIRC8zp3VMR6ccD_17x22DUN0yOszJGYDQMb6lV0rTiGyKzkMvSZ9mlDFdJPSaKTU_8kv5tTuRELHJTdfeH',
    category: 'electronics',
    description: 'Revolutionary magnetic levitation audio orb broadcasting true 360-degree high fidelity audio while floating beautifully above a solid marble power pad.',
    specs: {
      battery: '8 Hours Orb Autonomy',
      isolation: 'Zero Surface Distortion',
      range: 'Bluetooth 5.3 Active',
      latency: 'Acoustic Zero-lag Dual',
      weight: '1850g Total System',
      frequencyResponse: '35Hz - 25kHz Rich Base',
      driverDiameter: '60 mm Floating Core',
      charging: 'Wireless Induction Dock',
    }
  },
  {
    id: 'velvet-reading-throw',
    name: 'Cashmere Sovereign Throw',
    brand: 'OPAL',
    price: 165.00,
    rating: 4.8,
    reviewsCount: 29,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEaGaHx8YjKiVj6E3j7lxMVnqHAWSwAaXA-f3pKw6jpoId4_V34-jYXPU1_xTQPHq7FQwpJBbb6zIbw0OVHM8Fx8rHoW7PYjyvGhKU2b0z_o0KOfufWkIU5WRFzh82VaLZdvEMapehT7o1Zm_khusnEqSLPohwWO6Gr1-W61c32mX2Yk8WfvOFUVB1RCGPRI7hZlfE2yMN6WH3HLfetmmx-SqVGALlV6ymFzZ3SNy9TnmcEfGw1dDul8B-oxZlzOxnTdjgAj1vUC3F',
    category: 'home',
    description: 'Impeccable loom-woven cashmere soft throw designed for study chairs and cozy winter reading. Keeps body heat warm yet extremely breathable.',
    specs: {
      battery: 'N/A',
      isolation: 'Thermal Active Weave',
      range: 'Dimensions: 60 x 80 in',
      latency: 'Double sided luxury finish',
      weight: '800g Superlight Warmth',
      frequencyResponse: 'Hypoallergenic Organic',
      driverDiameter: 'Pure Cashmere Wool',
      charging: 'Dry Clean Recommended',
    }
  }
];

