import { Product } from './types';

export const CATEGORIES = [
  { id: 'electronics', name: 'Electronics', icon: 'devices' },
  { id: 'fashion', name: 'Fashion', icon: 'apparel' },
  { id: 'home', name: 'Home', icon: 'home' },
  { id: 'beauty', name: 'Beauty', icon: 'auto_awesome' },
  { id: 'sports', name: 'Sports', icon: 'fitness_center' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'studio-pro-x1',
    name: 'Studio Pro X1',
    brand: 'SONUS',
    price: 299.00,
    rating: 4.8,
    reviewsCount: 84,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEaGaHx8YjKiVj6E3j7lxMVnqHAWSwAaXA-f3pKw6jpoId4_V34-jYXPU1_xTQPHq7FQwpJBbb6zIbw0OVHM8Fx8rHoW7PYjyvGhKU2b0z_o0KOfufWkIU5WRFzh82VaLZdvEMapehT7o1Zm_khusnEqSLPohwWO6Gr1-W61c32mX2Yk8WfvOFUVB1RCGPRI7hZlfE2yMN6WH3HLfetmmx-SqVGALlV6ymFzZ3SNy9TnmcEfGw1dDul8B-oxZlzOxnTdjgAj1vUC3F',
    category: 'electronics',
    description: 'Experience professional acoustic performance with custom-tuned dynamic drivers, engineered for high-fidelity audio output and active isolation.',
    specs: {
      battery: '40 Hours',
      isolation: 'ANC Medium',
      range: '40 Feet',
      latency: 'Standard',
      weight: '270g',
      frequencyResponse: '20Hz - 20kHz',
      driverDiameter: '40 mm',
      charging: 'USB-C Cable',
    }
  },
  {
    id: 'luna-chrono',
    name: 'Luna Chrono',
    brand: 'HORIZON',
    price: 185.00,
    rating: 4.6,
    reviewsCount: 42,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5veSc6DQ8tMMnGq_C-UKN93MQn59O-hnvY5UUWKhaWwYhIluJvQQwHFqdV7P-tBcWsRBIHyl9l7T_sqmKIuActL8b4QLdFvwQdNvezvAXpzGH4QuadkMHQoxMoasVC9bpjETmCmLn5HqgSr4mJzhHr1_OXomU5gjQwn94kp4XUP1KUAWJ_WFHPGxQhFZjrWUa7UWy6e6-S8P0kK5NkDla8V4TFefTi4jedSKDHIsv_t1wheh_Wfxv3KYML2cAP4rXMRevqiuj75d4',
    category: 'fashion',
    description: 'A modern minimalist timepiece honoring the Swiss heritage of clarity and premium craftsmanship. Features a durable sapphire crystal dial and genuine hand-stitched leather strap.',
    specs: {
      battery: '12 Months',
      isolation: '3 ATM Water Resist',
      range: 'N/A',
      latency: 'Instant Swiss',
      weight: '62g',
      frequencyResponse: 'Analog Quartz',
      driverDiameter: '38 mm',
      charging: 'Button Cell',
    }
  },
  {
    id: 'opal-desk-light',
    name: 'Opal Desk Light',
    brand: 'OPAL',
    price: 120.00,
    rating: 4.7,
    reviewsCount: 56,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvHGah4EFhCaxFJ34u-vEx2G7Om8luw1eApLSsJeMP808VnwowdebOs3cZoOOaKpfou2CQ9LHnUEksSoKAe0SYFUCF1sl_s6_7XX_8xd15NlhTnd-iaqpC_dcFQnjYV0s0hcjXc6XbtaDEvEpzaU7YMN9TOpcbiLTzecGmp6jW1eBUQ4tdxlQtfTjCE-C7WVkSe5fS_OxXQi3JwmFU1Gd6-UnEoXIUobW1EaBQXZNONJyHBl3fpwY2NOg5RyoDOFLBcPLsh8MDFcjW',
    category: 'home',
    description: 'A designer ceramic desk lamp with a smooth matte finish, designed for bright ambient workspaces. Simulates gentle natural sunlight for stress-free eye comfort.',
    specs: {
      battery: 'N/A (Plugged)',
      isolation: 'Dual Hue Warm/Cool',
      range: 'Standard Cord',
      latency: 'Instant-on',
      weight: '1200g',
      frequencyResponse: '60Hz flicker-free',
      driverDiameter: 'LED Panel 120mm',
      charging: 'Wall adapter',
    }
  },
  {
    id: 'velocity-runner',
    name: 'Velocity Runner',
    brand: 'VELOCITY',
    price: 145.00,
    rating: 4.5,
    reviewsCount: 93,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWBo_ZkGTArM8ueR6RW3xqVGOamJ1cPBxuP0AH5BrzKL4QkGMX2Djg6ij7nG27Pl2XyrpFpFlcsxuhLJWnixmzF68MIXa6WxZ4pnkWUiCNcNMPYRIFuUvW9oJT3Els4dEdJ6XDmR3hH5USgiycEOajE-ExHA5Ht-7k-Cm79WMIDKxHm1btK25J_IGY2CLIB9iGwP68uSmmYK04gCZmOnxKGM0RkzqPJB5lFh-FR8U93hlVManrwBG7_S-Xwev7OtyJRXHBTfGQQrkV',
    category: 'sports',
    description: 'High-performance running sneakers incorporating responsive foam sole structure and breathable hyper-knit fabric wrapper for explosive energetic bounce.',
    specs: {
      battery: 'N/A',
      isolation: 'Heel-Lock Tech',
      range: 'All Terrain',
      latency: 'High Energy',
      weight: '235g',
      frequencyResponse: 'Impact Absorb',
      driverDiameter: 'Responsive Foam',
      charging: 'N/A',
    }
  },
  {
    id: 'onyx-chrono',
    name: 'Onyx Chrono',
    brand: 'HORIZON',
    price: 295.00,
    rating: 4.9,
    reviewsCount: 112,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_s6FNhJYRxymmc8zxwfikoISj0kXgvPks6U8mqSBHhC_sZbBPEI-gCGFUBWOVKITmURkS8GoyFcPNRHT9Q2oC0C-yLRJcrrbnIvRA4D2t5vZ8oUn2xRiHyYCKSX5NLbox8vr9AvuyHWTa3aq_rw2G7bv14ehDPsIHUOgBE1OxZElzcE6UA5Z4AExc1IIRC8zp3VMR6ccD_17x22DUN0yOszJGYDQMb6lV0rTiGyKzkMvSZ9mlDFdJPSaKTU_8kv5tTuRELHJTdfeH',
    category: 'fashion',
    description: 'Uncompromising prestige black-out wristware configured with genuine top-grain calfskin leather and precision flyback stopwatch dials. Elegantly robust.',
    specs: {
      battery: '24 Months',
      isolation: '5 ATM Water Resist',
      range: 'N/A',
      latency: 'Precision Flyback',
      weight: '75g',
      frequencyResponse: 'Quartz Japanese',
      driverDiameter: '42 mm',
      charging: 'Silver-oxide Cell',
    }
  },
  {
    id: 'aero-runner',
    name: 'Aero Runner',
    brand: 'VELOCITY',
    price: 180.00,
    rating: 4.7,
    reviewsCount: 65,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnwEnaqUQfIBJkSba2C4rYLXgzpU7WHgbYcbz-xTSe5Mk2F6mGhJpMRvP3IBubIZGd4RkmzoSQ8Sk3QufyDKUwsT4FpdaEVMefmA_x9Cq0sxaA1iA1atT73220M95ImkaN8MKGhdZN9iBYFevdfd02KKRd90k_HOSuB6rf8dlf_IHphNfXFGgTJj6pgSaRbcMkqzruORNZJ2F_6xDQxM4hEAB49fE0uhTzf_9HLo4UkrggzzrOdCszKhZLW5LWLbqRZiyLnuyAA1Sv',
    category: 'sports',
    description: 'Striking electric-blue trainers engineered for elite endurance track runs. Soft box layout ensures minimal friction with maximal ventilation.',
    specs: {
      battery: 'N/A',
      isolation: 'AeroBreathe Mesh',
      range: 'Track & Field',
      latency: 'Ultralight Sole',
      weight: '210g',
      frequencyResponse: 'Dynamic Spring',
      driverDiameter: 'Air Cushion',
      charging: 'N/A',
    }
  },
  {
    id: 'pure-audio-ii',
    name: 'Pure Audio II',
    brand: 'SONUS',
    price: 450.00,
    rating: 4.9,
    reviewsCount: 204,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgHSX_v_If7sjxq7lP4XaUvMUaw64TNL-dqgUkIDAzHrcaOwEjdIku_h3g8RHh9_nKwjIOJrMVusL5RU-urK4gz_WXriOLASCgi8tvO_BDC5HV0Ar8q4pP8kPE4DaJgq9jZx0YCyS5glEnx08XNiD0v0pmbK1OYuQUZXarcL7wDwB02IQbX77iwcoNjq_KeZVAlv-bSPAVLHgirTFzJgTSmieU34CKrpQQig-Mlw0W1eTJM_z6kOihvxhfuVkzC6khmUvw7nx_KT3X',
    category: 'electronics',
    description: 'Audiophile grade titanium over-ear sound transducers. Delivers pure atmospheric studio response with hyper-realistic instrument spatial layouts.',
    specs: {
      battery: '50 Hours',
      isolation: 'Closed Back Passive',
      range: 'Wireless & Corded',
      latency: 'Low Latency aptX',
      weight: '310g',
      frequencyResponse: '5Hz - 42kHz',
      driverDiameter: '50 mm',
      charging: 'USB-C SuperCharge',
    }
  },
  {
    id: 'nordic-mist',
    name: 'Nordic Mist',
    brand: 'ESSENCE',
    price: 120.00,
    rating: 4.4,
    reviewsCount: 38,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByRolG6h9kNjuuJl4UZqisGGfhWel-2NTJeDDfXr8Z4ECdsNJdpYdky0MHJ9lXwVAN9ueXe3daX3nz6B5yBoyrJIsaEzJGFTP9UuY7BGxOC-BIvv5_Bf2n3waJKo2at52FuJwFxeDh-ZhRnDtoy7Fn33HZlvgWYrAcRSllNlRe3tOTGqq2fxVZjAkx63PGJVKPZcWdVTrAme6kp_x99nsC9l_pfthTI4CYmX2hHgIhcmq2cXb3pab8HYoNVBh0AEgj36dK_jhewzAM',
    category: 'beauty',
    description: 'Delicate forest pine scent layered on pure glacial ocean breeze, encased beautifully within weighted modern glassware with heavy metallic top caps.',
    specs: {
      battery: 'N/A',
      isolation: 'Concentrated EDC',
      range: 'Long Lasting 8h',
      latency: 'Soft Sillage',
      weight: '100ml',
      frequencyResponse: 'Fragrance Profile',
      driverDiameter: 'Mist Atomizer',
      charging: 'Re-fillable',
    }
  },
  {
    id: 'tab-pro-x',
    name: 'Tab Pro X',
    brand: 'CORE',
    price: 899.00,
    rating: 4.8,
    reviewsCount: 152,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDqVcm2tYHn7BJwFWmQy9qx0Pe3xE3hibWuxHz0BHp_E4GbidH-_5R6K2ndm3fdTif6b3vKXhOZtxpu0iYbls5RJIHv2OeuSHuedXh1kD6ju7itV4bC2j1IPv9VWsv_NGtInb9Uv4rvL6FmGV0KbiTjpHfY6ssKarR0-5YKeeku15l5sGzZNPAFNd5dC5F3Vej247jvBTJ1e3uulieNmncvM9gXEj7U9KDsmhCb887Tus5IJSkpgfGckrnfJhKw_ZQtPW2lDmuN2I4m',
    category: 'electronics',
    description: 'An ultra-compact high-brightness designer productivity slate, supporting smooth multi-panel flows, accurate active stylet input tracking, and deep ambient sound system.',
    specs: {
      battery: '16 Hours',
      isolation: 'HDR10+ AMOLED',
      range: 'Wi-Fi 6E & 5G',
      latency: '120Hz Refresh',
      weight: '495g',
      frequencyResponse: 'Quad Atmos Speakers',
      driverDiameter: '11 inch Display',
      charging: 'USB-C 45W',
    }
  },
  {
    id: 'shadow-elite',
    name: 'Shadow Elite',
    brand: 'APEX',
    price: 210.00,
    rating: 4.8,
    reviewsCount: 77,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZAe_naQ6g4YsGa8gMzFtYO5dar6wyrMgo_zVjdc_L7WgVPTF0W2ZCjfKC7HQ4snkrEkKmRjHGjTqvUp4bE8RRxHhAAtsz1dChd15816sArRpWifd0b_aNNCbeuzDc4RAoqo9roSiB260PyPETzf91wp3STvAAWlBf_aNm_3iy0OYPYvC5dfmQrfmvsKnRuE58j3wX7P2RAPnPqhICLkZsx845s3dEjiYtoZmeXTbWFank-bgochxfn-kOYdhHaAFyuIOmGwGeOoSr',
    category: 'sports',
    description: 'Carbon fiber plate running shoes configured to shave precious seconds off your marathon target. Advanced high-bounce rubber heel rings provide responsive control.',
    specs: {
      battery: 'N/A',
      isolation: 'Carbon SpeedPlate',
      range: 'Road Marathon',
      latency: 'Ultra Responsive',
      weight: '195g',
      frequencyResponse: 'Traction Grip',
      driverDiameter: 'Energy Foam v2',
      charging: 'N/A',
    }
  },
  {
    id: 'apex-ultra-wireless',
    name: 'Apex Ultra Wireless',
    brand: 'APEX',
    price: 349.00,
    rating: 4.5,
    reviewsCount: 128,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBud-aefsBrsWBKhb2-Gmk8UL5UI8d-DM5KV09t9tLXoV7h4cZV2xwTOR6ikms20HylIc488bat-_5V03JpteV-FmHErkeUvKbawKo4RgZTg_aHboCS3gcnhbS3pCSDJMMzvjH_o6k0_55h6mQE4hR_abhXPLn1Nzp61rGZLetwHtgY9vDhBDqlRpU8Hy61TiU2Ax8qI0iGqQXxIw-k9ZJPyfjDpc8sy1m2m9uFwsV23u_F3Tga4Gv6yCTqsgcWwc3WBWqOAdb4RXW5',
    category: 'electronics',
    description: 'Engineered for those who demand acoustic perfection. The Apex Ultra features custom-tuned 40mm drivers and industry-leading noise cancellation technology, creating a sanctuary of sound even in the most chaotic environments. Crafted with memory foam and protein leather for all-day comfort.',
    specs: {
      battery: '60 Hours',
      isolation: 'ANC Max',
      range: '50 Feet',
      latency: 'Ultra Low',
      weight: '250g',
      frequencyResponse: '5Hz - 40kHz',
      driverDiameter: '40 mm',
      charging: 'USB-C Fast Charge',
    },
    additionalImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBud-aefsBrsWBKhb2-Gmk8UL5UI8d-DM5KV09t9tLXoV7h4cZV2xwTOR6ikms20HylIc488bat-_5V03JpteV-FmHErkeUvKbawKo4RgZTg_aHboCS3gcnhbS3pCSDJMMzvjH_o6k0_55h6mQE4hR_abhXPLn1Nzp61rGZLetwHtgY9vDhBDqlRpU8Hy61TiU2Ax8qI0iGqQXxIw-k9ZJPyfjDpc8sy1m2m9uFwsV23u_F3Tga4Gv6yCTqsgcWwc3WBWqOAdb4RXW5',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBv9zBBj41taJqrwt1LQAHM_jQk3Fd9ghuBGXArxuhColmK8SnPbnqqvNOOWiV243Acz0SfR6PRyqBxJ9yyPyISb5ejsrWyXKn5xrU5Ne5VPmWsmwCxzUKhdziv_OM1HYJUg0EW1nWYsK9dm1LspLVC-oVMpKldvvlPFirMJpWYLXW7UoYzCvypn8SnX04Y7ZAOs5RmOXGhdzWf51Yd9W9E3Vve9rN-aSYRWJxQLWmAB4KHGUZ2VYK7yELH721cv7lg7tYrZhGIRgw_'
    ]
  },
  {
    id: 'velocity-pro-runner',
    name: 'Velocity Pro-Runner',
    brand: 'VELOCITY',
    price: 180.00,
    rating: 4.6,
    reviewsCount: 78,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCEN_ZUkunDwbb4Eai6eFldv2pUeVKqv5N4HesABnkGp-h4JIss9AhVWWQRryXGhO2IEa6gMdyYjLYs-JVIGQHlRLxXMJuAPK_eavAwokF-rPEaPuMagQlyRSVMT3NG7lkM5hJmEeWvCyp87PPRDPexcO_Gq1iMZhlzu_MIwl2c0VVhkNMOh4xu9KoZQNKQgehoD2XWPzkY5j2_o4ebpkOpahHQ1PQx-c9Jz17I3iEC9yQ91fDeSw5ag9rjRRH7-hIeTVbo-3rox8U',
    category: 'sports',
    description: 'A professional premium electric blue runner. Styled seamlessly for maximum road endurance and stylish off-court presence.',
    specs: {
      battery: 'N/A',
      isolation: 'Stable Heel Support',
      range: 'All Terrain',
      latency: 'Lightweight Bounce',
      weight: '240g',
      frequencyResponse: 'Shock Absorption',
      driverDiameter: 'Active Foam Extra',
      charging: 'N/A',
    }
  },
  {
    id: 'luxe-chrono-white',
    name: 'Luxe Chrono White',
    brand: 'HORIZON',
    price: 350.00,
    rating: 4.8,
    reviewsCount: 121,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVFcfGtkLgYguIIwSvPgo5Dyft14CiZuo49THke4LSwityzptSIO5T-cLpaEdL8xibeXSzkrcZqwakoinFew3WfxPrwQuKEXTbvjRzaUd52bdUCBD4qJjFvyt4aBjWGrk7G96SxICAeXX1_fNZEjwn7Z0_3OgN626w0cbGE9G1VHCUcJEkzoCEQactaD3rQBjJKGftRQ-XtZpJSb0jIpVOYrNRhb8q7xANas4LWT88F_vixnSZO0kE_KCeN9d4COT4CclIdSxTqpl2',
    category: 'fashion',
    description: 'An elegant high-key white smart timepiece designed with a pristine polished casing, continuous heart activity sensor, and long-life battery cell.',
    specs: {
      battery: '7 Days Active',
      isolation: 'IP68 Swim-proof',
      range: 'BT 5.2 Secure',
      latency: 'Haptic Crown',
      weight: '55g',
      frequencyResponse: 'AMOLED Always-On',
      driverDiameter: '40 mm Dial',
      charging: 'Magnetic Puck',
    }
  },
  {
    id: 'acoustics-ultra-x',
    name: 'Acoustics Ultra X',
    brand: 'SONUS',
    price: 299.00,
    rating: 4.7,
    reviewsCount: 89,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAIlBoEmlDaffF029v3_Zdnz4iaiGAt6UNy942g5ptdeOEbq3nGIBPQP89OJrOfOB0INrN29Sfo1LcRQuMyf0UsoO99I8xAcuDV45w-WR18Ic98mZGsiWEaTEfCkQBpbmmYdr4ffjG4beJ53hegCcvrVKB7Ivgte-3pA1eKx9N_D2kd2G8xi9yv3lxpd_d_2xtGFihBv-cAVmAU3Z3cBbAw6e8at9LaZklSBeTYu_fsAmYXvA_v9YjLULbSPJizKCYt6loRWPv9haHX',
    category: 'electronics',
    description: 'Premium high-comfort noise canceling headphones designed for long audio mastering sessions, finished in a textured matte carbon texture with custom padded headband.',
    specs: {
      battery: '45 Hours',
      isolation: 'Advanced Hybrid ANC',
      range: '45 Feet',
      latency: 'Acoustic Zero-lag',
      weight: '265g',
      frequencyResponse: '10Hz - 35kHz',
      driverDiameter: '40 mm Custom',
      charging: 'USB-C Fast Charge',
    }
  },
  {
    id: 'aurora-skin-regenerator',
    name: 'Aurora Laser Wand',
    brand: 'ESSENCE',
    price: 380.00,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvHGah4EFhCaxFJ34u-vEx2G7Om8luw1eApLSsJeMP808VnwowdebOs3cZoOOaKpfou2CQ9LHnUEksSoKAe0SYFUCF1sl_s6_7XX_8xd15NlhTnd-iaqpC_dcFQnjYV0s0hcjXc6XbtaDEvEpzaU7YMN9TOpcbiLTzecGmp6jW1eBUQ4tdxlQtfTjCE-C7WVkSe5fS_OxXQi3JwmFU1Gd6-UnEoXIUobW1EaBQXZNONJyHBl3fpwY2NOg5RyoDOFLBcPLsh8MDFcjW',
    category: 'beauty',
    description: 'Advanced medical-grade micro-current and red-light wand designed to restore skin vigor, smoothen wrinkles, and offer natural spa-level lifting at home.',
    specs: {
      battery: '3 Hours Continuous',
      isolation: 'Hypoallergenic Titanium',
      range: 'USB Wireless Charging Base',
      latency: 'Instant Radiant Output',
      weight: '85g',
      frequencyResponse: '630nm Wave Length',
      driverDiameter: '360° Rotating Head',
      charging: 'Magnetic Wireless Stand',
    }
  },
  {
    id: 'luna-gold-necklace',
    name: '24K Solstice Chain',
    brand: 'HORIZON',
    price: 750.00,
    rating: 5.0,
    reviewsCount: 31,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEaGaHx8YjKiVj6E3j7lxMVnqHAWSwAaXA-f3pKw6jpoId4_V34-jYXPU1_xTQPHq7FQwpJBbb6zIbw0OVHM8Fx8rHoW7PYjyvGhKU2b0z_o0KOfufWkIU5WRFzh82VaLZdvEMapehT7o1Zm_khusnEqSLPohwWO6Gr1-W61c32mX2Yk8WfvOFUVB1RCGPRI7hZlfE2yMN6WH3HLfetmmx-SqVGALlV6ymFzZ3SNy9TnmcEfGw1dDul8B-oxZlzOxnTdjgAj1vUC3F',
    category: 'fashion',
    description: 'Expertly forged hand-crafted 24K pure gold necklace featuring a classic woven chain link system and single brilliant ethically-sourced diamond accent.',
    specs: {
      battery: 'Eternal Lifetime',
      isolation: 'Water/Heat Resistant',
      range: 'Length: 22 inches',
      latency: 'Master Craftsman Forged',
      weight: '45g Pure Gold',
      frequencyResponse: 'Brilliant Diamond Cut',
      driverDiameter: '5 mm width',
      charging: 'No Charging Required',
    }
  },
  {
    id: 'zenith-smart-mat',
    name: 'Zenith Interactive Yoga Mat',
    brand: 'VELOCITY',
    price: 245.00,
    rating: 4.8,
    reviewsCount: 54,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWBo_ZkGTArM8ueR6RW3xqVGOamJ1cPBxuP0AH5BrzKL4QkGMX2Djg6ij7nG27Pl2XyrpFpFlcsxuhLJWnixmzF68MIXa6WxZ4pnkWUiCNcNMPYRIFuUvW9oJT3Els4dEdJ6XDmR3hH5USgiycEOajE-ExHA5Ht-7k-Cm79WMIDKxHm1btK25J_IGY2CLIB9iGwP68uSmmYK04gCZmOnxKGM0RkzqPJB5lFh-FR8U93hlVManrwBG7_S-Xwev7OtyJRXHBTfGQQrkV',
    category: 'sports',
    description: 'Smart exercise pad configured with pressure-sensitive haptic sensors and guiding LED light indicators for flawless pose correction and balanced flow.',
    specs: {
      battery: '12 Hours Usage',
      isolation: 'Shock-absorbing Grip Base',
      range: 'BT 5.1 App Sync',
      latency: 'Real-time Positional Feed',
      weight: '1600g',
      frequencyResponse: 'Pressure Grid Dynamic',
      driverDiameter: '72 x 24 inches',
      charging: 'USB-C Cable',
    }
  },
  {
    id: 'levitate-ambient-sound',
    name: 'Levitate Floating Orb',
    brand: 'SONUS',
    price: 599.00,
    rating: 4.9,
    reviewsCount: 68,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_s6FNhJYRxymmc8zxwfikoISj0kXgvPks6U8mqSBHhC_sZbBPEI-gCGFUBWOVKITmURkS8GoyFcPNRHT9Q2oC0C-yLRJcrrbnIvRA4D2t5vZ8oUn2xRiHyYCKSX5NLbox8vr9AvuyHWTa3aq_rw2G7bv14ehDPsIHUOgBE1OxZElzcE6UA5Z4AExc1IIRC8zp3VMR6ccD_17x22DUN0yOszJGYDQMb6lV0rTiGyKzkMvSZ9mlDFdJPSaKTU_8kv5tTuRELHJTdfeH',
    category: 'electronics',
    description: 'Revolutionary magnetic levitation audio orb broadcasting true 360-degree high fidelity audio while floating beautifully above a solid marble power pad.',
    specs: {
      battery: '8 Hours Orb Autonomy',
      isolation: 'Zero Surface Distortion',
      range: 'Bluetooth 5.3 Active',
      latency: 'Acoustic Zero-lag Dual',
      weight: '1850g Total System',
      frequencyResponse: '35Hz - 25kHz Rich Base',
      driverDiameter: '60 mm Floating Core',
      charging: 'Wireless Induction Dock',
    }
  },
  {
    id: 'velvet-reading-throw',
    name: 'Cashmere Sovereign Throw',
    brand: 'OPAL',
    price: 165.00,
    rating: 4.8,
    reviewsCount: 29,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEaGaHx8YjKiVj6E3j7lxMVnqHAWSwAaXA-f3pKw6jpoId4_V34-jYXPU1_xTQPHq7FQwpJBbb6zIbw0OVHM8Fx8rHoW7PYjyvGhKU2b0z_o0KOfufWkIU5WRFzh82VaLZdvEMapehT7o1Zm_khusnEqSLPohwWO6Gr1-W61c32mX2Yk8WfvOFUVB1RCGPRI7hZlfE2yMN6WH3HLfetmmx-SqVGALlV6ymFzZ3SNy9TnmcEfGw1dDul8B-oxZlzOxnTdjgAj1vUC3F',
    category: 'home',
    description: 'Impeccable loom-woven cashmere soft throw designed for study chairs and cozy winter reading. Keeps body heat warm yet extremely breathable.',
    specs: {
      battery: 'N/A',
      isolation: 'Thermal Active Weave',
      range: 'Dimensions: 60 x 80 in',
      latency: 'Double sided luxury finish',
      weight: '800g Superlight Warmth',
      frequencyResponse: 'Hypoallergenic Organic',
      driverDiameter: 'Pure Cashmere Wool',
      charging: 'Dry Clean Recommended',
    }
  },
  {
    id: 'luxe-anc-earbuds',
    name: 'Acoustics Air Pods Pro',
    brand: 'SONUS',
    price: 199.00,
    rating: 4.7,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Miniature true-wireless elite earbuds supporting hybrid ANC, adaptive transparency mode, sound virtualization and standard sweat resistance.',
    specs: {
      battery: '8 Hours (30h with Case)',
      isolation: 'Active Noise Cancelling',
      range: '50 Feet Bluetooth 5.3',
      latency: '45ms Low Latency Option',
      weight: '5.4g per earbud',
      frequencyResponse: '20Hz - 22kHz',
      driverDiameter: '11mm Dynamic',
      charging: 'Wireless Qi + USB-C',
    }
  },
  {
    id: 'carbon-hybrid-watch',
    name: 'Carbon Hybrid Prestige',
    brand: 'HORIZON',
    price: 450.00,
    rating: 4.9,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Striking carbon composite and ceramic bezel timepiece featuring illuminated mechanical hands, integrated heartbeat logs, and high-end sapphire dial crystal.',
    specs: {
      battery: '14 Days Smart-Mode',
      isolation: '5 ATM Water Resistant',
      weight: '52g Featherweight',
      frequencyResponse: 'Automated Hybrid Movement',
      driverDiameter: '42mm Carbon Dial',
      charging: 'Magnetic Rapid Dock',
    }
  },
  {
    id: 'silk-sleep-mask',
    name: 'Mulberry Royal Sleep Set',
    brand: 'ESSENCE',
    price: 45.00,
    rating: 4.8,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: '100% pure Mulberry silk sleep mask paired with a matching satin carrying pouch, protecting skin delicate layers and preventing fine lines all night.',
    specs: {
      isolation: '100% Light Blockout',
      weight: '15g Ultra Light',
      frequencyResponse: 'Hypoallergenic Silk',
      driverDiameter: 'Wide fit strap',
      charging: 'Gentle Hand-wash',
    }
  },
  {
    id: 'smart-touch-kettle',
    name: 'Precision Thermostat Kettle',
    brand: 'OPAL',
    price: 115.00,
    rating: 4.6,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Designer matte-black double-wall kettle with precision pour gooseneck spout and digital OLED temp controllers for professional matcha extraction.',
    specs: {
      range: '1200 Watts Fast Boil',
      weight: '1.1kg',
      frequencyResponse: 'Realtime Temp Sensing',
      driverDiameter: '0.9L Capacity',
      charging: 'Rotatable power base',
    }
  },
  {
    id: 'titanium-water-bottle',
    name: 'Thermos Titanium Flask',
    brand: 'APEX',
    price: 80.00,
    rating: 4.9,
    reviewsCount: 34,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Elite grade single-wall pure titanium hydration bottle, completely flavor-neutral, corrosion-free, and incredibly durable for extreme mountaineering.',
    specs: {
      isolation: 'Double-Wall Vacuum Keep',
      weight: '160g Featherweight',
      range: 'All Weather Proof',
      frequencyResponse: 'BPA-Free / Toxin-Free',
      driverDiameter: '750ml Capacity',
    }
  },
  {
    id: 'leather-travel-duffel',
    name: 'Sovereign Travel Duffel',
    brand: 'HORIZON',
    price: 290.00,
    rating: 4.9,
    reviewsCount: 47,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Impeccable hand-grained full calfskin duffel bag configured with high-strength solid brass buckles, separate shoe compartments, and padded laptop sleeve.',
    specs: {
      weight: '1.4kg empty',
      range: '45L Cabin Approved',
      driverDiameter: 'Full Grain Leather',
    }
  },
  {
    id: 'magnetic-wireless-hub',
    name: 'Orb Wireless Power Pad',
    brand: 'CORE',
    price: 95.00,
    rating: 4.7,
    reviewsCount: 79,
    image: 'https://images.unsplash.com/photo-1622445262465-2481c4574875?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Full solid CNC aluminum charging desk dock delivering 15W high speed magnetic juice to three personal devices simultaneously.',
    specs: {
      isolation: 'Overheat Protection Guard',
      range: '15W MagSafe Compliant',
      weight: '210g Stable Base',
      charging: 'USB-C input 30W adapter',
    }
  },
  {
    id: 'royal-velvet-pillow',
    name: 'Orthopedic Velvet Sleep Cushion',
    brand: 'OPAL',
    price: 65.00,
    rating: 4.5,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Contoured premium density slow-rebound memory foam neck pillow with silky royal velvet outer shell for cervical posture correction.',
    specs: {
      isolation: 'Airflow Breathable Core',
      weight: '900g Cushioning',
      driverDiameter: 'Dimensions: 60 x 35 x 11 cm',
    }
  },
  {
    id: 'gold-plated-eyewear',
    name: 'Aviation 18K Luxury Aviators',
    brand: 'HORIZON',
    price: 310.00,
    rating: 4.9,
    reviewsCount: 71,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Superb 18K real gold plated surgical frame aviator eyewear equipped with premium Carl Zeiss polarized anti-glare high-spec lenses.',
    specs: {
      isolation: '100% UVA/UVB Protection',
      weight: '28g Ultralight',
      driverDiameter: 'Zeiss Carbon Lens 58mm',
    }
  },
  {
    id: 'vitamin-c-serum',
    name: 'Celestial Vitamin C Elixir',
    brand: 'ESSENCE',
    price: 75.00,
    rating: 4.7,
    reviewsCount: 168,
    image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'High-potency 20% Vitamin C serum enhanced with Ferulic acid and pure Hyaluronic base to instantly brighten hyperpigmented skin layers and fight oxidative wear.',
    specs: {
      weight: '30ml Dropper Bottle',
      frequencyResponse: 'pH Balanced 3.2',
    }
  },
  {
    id: 'carbon-badminton-set',
    name: 'HyperWave Carbon Badminton Duo',
    brand: 'APEX',
    price: 185.00,
    rating: 4.8,
    reviewsCount: 23,
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Professional high-tension carbon fiber rackets set packed in an airtight thermal protection sleeve with three real goose-feather competition shuttles.',
    specs: {
      weight: '78g each Superlight',
      range: '30 lbs Tension Max',
      frequencyResponse: 'Ultra-stiff graphite shaft',
    }
  },
  {
    id: 'smart-aroma-diffuser',
    name: 'Nebulizer Ambient Oil Diffuser',
    brand: 'OPAL',
    price: 140.00,
    rating: 4.8,
    reviewsCount: 41,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Waterless luxury cold-mist pure home scent diffuser with full smartphone app connection and customizable schedules.',
    specs: {
      range: 'Covers up to 1000 sq ft',
      weight: '450g',
      charging: 'Wall socket plug',
    }
  },
  {
    id: 'high-fidelity-soundbar',
    name: 'Symphony Atmos Soundbar v9',
    brand: 'SONUS',
    price: 699.00,
    rating: 4.9,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Ultra-slim 7.1.2 Dolby Atmos spatial audio bar with deep wireless active subwoofer and calibrated space acoustic microphones.',
    specs: {
      range: '500 Watt RMS System Power',
      weight: '8.4kg System Weight',
      frequencyResponse: '28Hz - 20kHz',
      driverDiameter: '9 High-Performance Transducers',
      charging: 'Direct AC Cable',
    }
  },
  {
    id: 'cashmere-knit-scarf',
    name: 'Imperial Cashmere Winter Scarf',
    brand: 'HORIZON',
    price: 110.00,
    rating: 4.8,
    reviewsCount: 46,
    image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Exquisitely soft, heavyweight 100% pure cashmere wool winter neck scarf woven in small batches in a family mill.',
    specs: {
      weight: '320g Weighty Warmth',
      range: 'Dimensions: 180 x 30 cm',
    }
  },
  {
    id: 'premium-matcha-kit',
    name: 'Imperial Ceremonial Matcha Set',
    brand: 'ESSENCE',
    price: 90.00,
    rating: 5.0,
    reviewsCount: 19,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Traditional organic skincare and ceremonial wellness pack featuring high-grade Uji matcha powder, hand-carved golden bamboo whisk, and classic ceramic bowl.',
    specs: {
      weight: '30g Matcha Can + Kit',
      frequencyResponse: '100% Certified Organic',
    }
  },
  {
    id: 'ergonomic-office-chair',
    name: 'Apex Orthopedic Mesh Throne',
    brand: 'OPAL',
    price: 480.00,
    rating: 4.7,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Designed for elite remote workspace comfort. Features adaptive mechanical lumbar tracking, 4D armrests, and 135-degree deep tilt lock mesh casing.',
    specs: {
      weight: '18kg',
      range: 'Supports up to 150kg',
      driverDiameter: 'High Tension Elastic Mesh',
    }
  },
  {
    id: 'ultra-grip-dumbbells',
    name: 'Hexagon Cast Iron Dumbbells Pair',
    brand: 'APEX',
    price: 150.00,
    rating: 4.8,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Premium rust-free textured rubber encased solid iron dumbbells with comfortable ergonomic anti-slip chrome handles.',
    specs: {
      weight: '20kg Pair (10kg each)',
      isolation: 'Anti-roll Hexagonal Edge',
    }
  },
  {
    id: 'hydrating-algae-mask',
    name: 'Marine Algae Hydration Gel',
    brand: 'ESSENCE',
    price: 60.00,
    rating: 4.6,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Instant soothing oceanic cooling gel mask formulated with Icelandic kelp extract and spirulina to replenish dry and fatigued facial skin structures.',
    specs: {
      weight: '100ml Matte Tub',
      frequencyResponse: 'Zero fragrance / Vegan',
    }
  },
  {
    id: 'dual-laser-projector',
    name: 'VividCinema 4K Laser Hub',
    brand: 'CORE',
    price: 1250.00,
    rating: 4.9,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'High-end short throw 4K laser projection engine generating up to 150 inches of crystal-clear cinematic canvas with built-in Harman Kardon audio system.',
    specs: {
      range: '2800 ANSI Lumens Brightness',
      weight: '5.2kg Engine',
      frequencyResponse: 'Dual Harman Kardon 15W Speakers',
      driverDiameter: '0.23 Short-Throw Laser Range',
      charging: 'AC Cord Power',
    }
  },
  {
    id: 'rebound-tennis-racket',
    name: 'Pro-Spin Graphite Tennis Racket',
    brand: 'APEX',
    price: 220.00,
    rating: 4.8,
    reviewsCount: 57,
    image: 'https://images.unsplash.com/photo-1622279457486-62dcc4a4dd93?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Aerodynamic carbon fiber and woven kevlar tennis racket offering unparalleled top-spin speed and impact dampening for competitive court tennis.',
    specs: {
      weight: '295g unstrungweight',
      isolation: 'VibeShield Grip Guard',
      range: 'Head size: 98 sq in',
    }
  },
  {
    id: 'leather-wallet-classic',
    name: 'Classic Calfskin Card Holder',
    brand: 'HORIZON',
    price: 85.00,
    rating: 4.8,
    reviewsCount: 134,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Exquisite hand-stitched grain calfskin wallet with sleek card storage bays, RFID defensive layer and golden embossed company seal.',
    specs: {
      weight: '45g Featherweight',
      isolation: 'RFID Blockout Enabled',
      range: '6 card compartments',
    }
  },
  {
    id: 'wireless-keyboard-retro',
    name: 'Mechanical Retro Typing Canvas',
    brand: 'CORE',
    price: 180.00,
    rating: 4.9,
    reviewsCount: 92,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Exquisite tactile typing deck inspired by historical typewriters. Features authentic mahogany mechanical keys with premium gold-plated switches and dual iOS/OSX modes.',
    specs: {
      battery: '3 Months Standby',
      isolation: 'Blue-switch Tactile Clank',
      range: 'Bluetooth 5.2 / Wire dual',
      charging: 'USB-C Charging Dock',
    }
  },
  {
    id: 'scented-candle-sandall',
    name: 'Sandalwood Amber Luxury Mist',
    brand: 'ESSENCE',
    price: 40.00,
    rating: 4.7,
    reviewsCount: 55,
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Eco-soy luxury scented candle poured into a mouth-blown charcoal glass holder, radiating a beautiful deep profile of aged sandalwood, golden cedar and warm patchouli.',
    specs: {
      weight: '220g Premium Pour',
      isolation: '60 Hours Slow Clean Burn',
    }
  },
  {
    id: 'espresso-machine-compact',
    name: 'Gourmet Extraction Espresso Lever',
    brand: 'OPAL',
    price: 320.00,
    rating: 4.9,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Solid brass lever piston hot-extraction coffee machinery designed for elite micro-foam creation and professional grade crema levels at home.',
    specs: {
      range: '15 Bars Extraction Pressure',
      weight: '4.8kg Sturdy Metal Body',
    }
  },
  {
    id: 'running-backpack-light',
    name: 'AeroShell Hydration Sports Vest',
    brand: 'APEX',
    price: 110.00,
    rating: 4.6,
    reviewsCount: 47,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Zero-bounce ergonomic trail runner backpack complete with a 1.5L platinum leak-proof bladder, insulated tube layer and responsive compression cord adjustment.',
    specs: {
      weight: '240g Base Weight',
      range: '1.5 Liters Reservoir Included',
    }
  },
  {
    id: 'silk-pyjama-set',
    name: 'Elysium Silk Loungewear Pyjamas',
    brand: 'ESSENCE',
    price: 195.00,
    rating: 4.9,
    reviewsCount: 63,
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Indulgently soft, 100% fine mulberry silk button-down nightwear paired with comfortable relaxed-fit trousers. Gentle on skin barriers and keeps you beautifully cool.',
    specs: {
      weight: '290g Soft Drape',
      isolation: 'Hypoallergenic Natural Silk',
    }
  },
  {
    id: 'anc-headphones-silver',
    name: 'AeroTone Active ANC Headphones',
    brand: 'SONUS',
    price: 299.00,
    rating: 4.8,
    reviewsCount: 228,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Comfortable over-ear studio monitors leveraging 43dB active hybrid room cancellation, pristine vocal frequency isolation and master-tuned 40mm beryllium drivers.',
    specs: {
      battery: '45 Hours ANC On Playback',
      isolation: '43dB Master Room Cancel',
      range: 'Bluetooth 5.3 + AUX input',
      charging: 'Rapid Fill: 10 mins = 5h',
    }
  },
  {
    id: 'smart-temperature-mug',
    name: 'Thermostat Self-Heating Smart Mug',
    brand: 'OPAL',
    price: 75.00,
    rating: 4.5,
    reviewsCount: 119,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Fine ceramic smart cup that maintains your perfect tea or premium drip coffee temperature precisely all day. Controlled seamlessly via local capacitive interface.',
    specs: {
      battery: '2 Hours off the base coaster',
      range: 'Temp limits: 50°C - 62.5°C',
    }
  },
  {
    id: 'premium-leather-belt',
    name: 'Signature Full Grain Leather Strap',
    brand: 'HORIZON',
    price: 95.00,
    rating: 4.8,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1624222247344-550fb8ecf7db?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Indestructible full-grain genuine leather dress belt equipped with a classic solid brass luxury buckle mechanism, burnished by hand to an elegant sheen.',
    specs: {
      weight: '120g Heavyweight Cut',
      range: 'Available fits: 30 to 44 in',
    }
  },
  {
    id: 'charcoal-cleansing-gel',
    name: 'Carbon Volcanic Pore Cleanser',
    brand: 'ESSENCE',
    price: 35.00,
    rating: 4.7,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Detoxifying charcoal facial gel utilizing botanical extracts, salicylic acid and oceanic sea silt minerals to lift deep cellular impurities and minimize visible pores.',
    specs: {
      weight: '150ml Amber Pump Bottle',
      frequencyResponse: 'pH Balanced 5.5',
    }
  },
  {
    id: 'titanium-table-lamp',
    name: 'Saturn Brass Halo Desk Lamp',
    brand: 'OPAL',
    price: 160.00,
    rating: 4.9,
    reviewsCount: 31,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Minimalist brushed-brass desktop light piece projecting an ultra-soft, completely flicker-free ambient aura. Built-in responsive continuous touch slide dimmer.',
    specs: {
      range: 'CRI 95 Pristine Rendering Index',
      weight: '2.1kg Weighted Base',
    }
  },
  {
    id: 'carbon-hiking-poles',
    name: 'Summit Carbon Composite Pillars',
    brand: 'APEX',
    price: 95.00,
    rating: 4.8,
    reviewsCount: 26,
    image: 'https://images.unsplash.com/photo-1531860898434-a518ee143f24?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'High-strength 100% real carbon hiking poles paired with natural sweat-wicking cork handles. Complete with shock-absorbing smart suspension modules.',
    specs: {
      weight: '185g each stick',
      range: 'Adjustable range: 100 - 135 cm',
    }
  },
  {
    id: 'acoustic-bookshelf-speaker',
    name: 'Acoustic Walnut Desk Speakers',
    brand: 'SONUS',
    price: 420.00,
    rating: 4.9,
    reviewsCount: 74,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'High performance active bookshelf speaker pair finished in gorgeous real walnut timber, delivering breathtaking audiophile room dynamics and sound virtualization.',
    specs: {
      range: '120 Watts Dual System Power',
      frequencyResponse: '45Hz - 22kHz Dynamic Range',
    }
  },
  {
    id: 'wool-tweed-jacket',
    name: 'Sovereign Wool Tweed Blazer',
    brand: 'HORIZON',
    price: 380.00,
    rating: 4.7,
    reviewsCount: 41,
    image: 'https://images.unsplash.com/photo-1598808503746-f34c53b29ef3?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'Luxurious heavy-weighted heritage tweed jacket, tailormade with soft silk inner lining, structured shoulder peaks and signature leather buttons.',
    specs: {
      weight: '1.2kg Heritage Weave',
      isolation: 'Thermal Winter Compliant',
    }
  },
  {
    id: 'caviar-face-balm',
    name: 'Imperial Caviar Restoring Balm',
    brand: 'ESSENCE',
    price: 125.00,
    rating: 4.9,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=600&q=80',
    category: 'beauty',
    description: 'Rich organic face elixir infused with highly sought-after sturgeon caviar micro-molecules and gold leaf flakes to dramatically accelerate elastin production.',
    specs: {
      weight: '50ml Glass Pot',
      frequencyResponse: 'Natural / Cruelty Free',
    }
  },
  {
    id: 'minimalist-concrete-clock',
    name: 'Brutalist Concrete Office Chrono',
    brand: 'OPAL',
    price: 130.00,
    rating: 4.6,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=600&q=80',
    category: 'home',
    description: 'Stunning table desk timepiece cast by hand in high-grade architectural aggregate, equipped with silent sweeping German quartz motion hands.',
    specs: {
      battery: '1x AA Battery (Included)',
      weight: '1.5kg Solid Aggregate',
    }
  },
  {
    id: 'ergonomic-vertical-mouse',
    name: 'Glider Ergonomic Precision Mouse',
    brand: 'CORE',
    price: 110.00,
    rating: 4.8,
    reviewsCount: 156,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    category: 'electronics',
    description: 'Ergonomic 57-degree natural handshake posture mouse, specifically engineered to completely eliminate forearm torsion and repetitive wrist strain.',
    specs: {
      battery: 'Up to 4 Months (Rechargeable)',
      range: 'Adjustable 4000 DPI Precision',
      charging: 'USB-C Cable',
    }
  },
  {
    id: 'smart-jump-rope',
    name: 'AeroSpin Speed Haptic Jump Rope',
    brand: 'APEX',
    price: 65.00,
    rating: 4.7,
    reviewsCount: 51,
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Pro speed skipping cable containing custom handle ball bearings, high-resolution haptic rotation counters, and smart Bluetooth workout tracker.',
    specs: {
      battery: '30 Days Active Tracking',
      range: '3 Meter Fully Adjustable Cable',
    }
  },
  {
    id: 'massage-gun-pro',
    name: 'DeepTissue Pulsar Muscle Reliever',
    brand: 'VELOCITY',
    price: 210.00,
    rating: 4.9,
    reviewsCount: 118,
    image: 'https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?auto=format&fit=crop&w=600&q=80',
    category: 'sports',
    description: 'Powerful handheld multi-speed wellness massage gun generating up to 3200 strokes per minute to actively relieve body knots and promote recovery cycles.',
    specs: {
      battery: '5 Hours Smart Life',
      weight: '980g Ergonomic Frame',
      charging: 'Fast magnetic charge dock',
    }
  },
  {
    id: 'luxe-travel-organizer',
    name: 'Vanguard Tech Organizer Sleeve',
    brand: 'CORE',
    price: 75.00,
    rating: 4.8,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    category: 'fashion',
    description: 'A pocket-dense tech accessory case structured with custom stretchable loops, waterproof zip-lining, and premium pebble leather casing.',
    specs: {
      weight: '180g Empty weight',
      isolation: 'IP54 Weather Resistant',
    }
  }
];

